#!/bin/sh
cd datacards 

for higgsMass in 90 100 120 130 140 160 180 200 250 300 350 400 450 500 
do
combineCards.py muTau=muTau_X_mA$higgsMass.txt eleTau=eleTau_X_mA$higgsMass.txt eleMu=eleMu_X_mA$higgsMass.txt >Comb_X_mA$higgsMass.txt

done




