#!/bin/sh
cd datacards 

for higgsMass in 90 100 120 130 140 160 180 200 250 300 350 400 450 500 
do
combineCards.py B=muTau_B_mA$higgsMass.txt  NoB=muTau_NoB_mA$higgsMass.txt  > muTau_BTag_mA$higgsMass.txt
combineCards.py B=eleTau_B_mA$higgsMass.txt NoB=eleTau_NoB_mA$higgsMass.txt > eleTau_BTag_mA$higgsMass.txt
combineCards.py B=eleMu_B_mA$higgsMass.txt  NoB=eleMu_NoB_mA$higgsMass.txt  > eleMu_BTag_mA$higgsMass.txt
combineCards.py muTau=muTau_BTag_mA$higgsMass.txt eleTau=eleTau_BTag_mA$higgsMass.txt eleMu=eleMu_BTag_mA$higgsMass.txt >Comb_BTag_mA$higgsMass.txt

done




