#include "UWAnalysis/PatTools/plugins/DiCandidatePairSelector.h"

#include "FWCore/Framework/interface/MakerMacros.h"

DEFINE_FWK_MODULE(DiCandidatePairSelector);
DEFINE_FWK_MODULE(DiCandidatePairRefSelector);
DEFINE_FWK_MODULE(PATMuTauPairSelector);
DEFINE_FWK_MODULE(PATMuJetPairSelector);
DEFINE_FWK_MODULE(PATDiTauPairSelector);
DEFINE_FWK_MODULE(PATMuTrackPairSelector);
DEFINE_FWK_MODULE(PATEleTrackPairSelector);
DEFINE_FWK_MODULE(PATMuPairSelector);
DEFINE_FWK_MODULE(PATEleMuPairSelector);
DEFINE_FWK_MODULE(PATEleTauPairSelector);
DEFINE_FWK_MODULE(PATEleSCPairSelector);
DEFINE_FWK_MODULE(PATElePairSelector);

DEFINE_FWK_MODULE(PATMuMuMuTauQuadSelector);
DEFINE_FWK_MODULE(PATMuMuTauTauQuadSelector);
DEFINE_FWK_MODULE(PATMuMuEleTauQuadSelector);
DEFINE_FWK_MODULE(PATMuMuEleMuQuadSelector);
DEFINE_FWK_MODULE(PATMuMuMuMuQuadSelector);
DEFINE_FWK_MODULE(PATMuMuEleEleQuadSelector);
DEFINE_FWK_MODULE(PATEleEleEleTauQuadSelector);
DEFINE_FWK_MODULE(PATEleEleTauTauQuadSelector);
DEFINE_FWK_MODULE(PATEleEleEleEleQuadSelector);
DEFINE_FWK_MODULE(PATEleEleMuTauQuadSelector);
DEFINE_FWK_MODULE(PATEleEleEleMuQuadSelector);
DEFINE_FWK_MODULE(PATEleEleMuMuQuadSelector);
DEFINE_FWK_MODULE(PATEleEleEleSCQuadSelector);
DEFINE_FWK_MODULE(PATEleSCEleEleQuadSelector);
DEFINE_FWK_MODULE(PATMuMuEleSCQuadSelector);
DEFINE_FWK_MODULE(PATEleSCMuMuQuadSelector);

DEFINE_FWK_MODULE(PATEleEleEleTriSelector);
DEFINE_FWK_MODULE(PATEleEleMuTriSelector);
DEFINE_FWK_MODULE(PATMuMuEleTriSelector);
DEFINE_FWK_MODULE(PATMuMuMuTriSelector);

