{

#include <fstream>
	gROOT->ProcessLine(".L /afs/hep.wisc.edu/cms/iross/HZZ2l2tau/CMSSW_4_2_5/src/UWAnalysis/ROOT/interactive/tdrstyle.C");
	gROOT->ProcessLine(".L /afs/hep.wisc.edu/cms/iross/HZZ2l2tau/CMSSW_4_2_5/src/UWAnalysis/ROOT/macros/ZZLimitsAndYields/helpers.h");
	gROOT->Reset();
	setTDRStyle();
	//	setStyle();
	ofstream fRstream;
	fRstream.open("fakeRates");
	TFile *e = new TFile("sandbox/zz-latest/DATA.root");
	TFile *m = new TFile("sandbox/zz-latest/DATA.root");
	TFile *e = new TFile("BGStdIso_17May.root");
	TFile *m = new TFile("BGStdIso_17May.root");

	TString LEleZ = "HLT_Any&&z1Mass>60&&z1Mass<120&&(z1l1CiCTight&1)==1&&(z1l2CiCTight&1)==1&&z1l1MissHits<2&&z1l2MissHits<2&&"+stdIso("z1l1",0.275,"ele")+"&&"+stdIso("z1l2",0.275,"ele")+"&&z1l1Pt>20&&z1l2Pt>10&&z1l1SIP<4&&z1l2SIP<4";
	TString LMuZ = "HLT_Any&&z1Mass>60&&z1Mass<120&&"+stdIso("z1l1",0.275,"mu")+"&&"+stdIso("z1l2",0.275,"mu")+"&&z1l1Pt>20&&z1l2Pt>10&&z1l1SIP<4&&z1l2SIP<4";

	TString STTZt1n = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1MediumIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
	TString STTZt2n = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l2MediumIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
	TString STTZt1nVL = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1LooseIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
	TString STTZt2nVL = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l2LooseIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
	TString STTZt1d  = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
	TString STTZt2d  = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";

	TString SEEZ2n = "&&z2l2Pt>7&&z2Charge!=0&&"+stdIso("z2l2",0.275,"ele")+"&&met<20&&z2l2SIP<4";
	TString SEEZ1n = "&&z2l1Pt>7&&z2Charge!=0&&"+stdIso("z2l1",0.275,"ele")+"&&met<20&&z2l1SIP<4";
	TString SMMZ2n = "&&z2l2Pt>5&&z2Charge!=0&&"+stdIso("z2l2",0.275,"mu")+"&&met<20&&z2l2SIP<4";
	TString SMMZ1n = "&&z2l1Pt>5&&z2Charge!=0&&"+stdIso("z2l1",0.275,"mu")+"&&met<20&&z2l1SIP<4";
	TString SEMZMn = "&&z2l2Pt>5&&"+stdIso("z2l2",0.275,"mu")+"&&z2Charge!=0&&met<20&&z2l1SIP<4";
	TString SEMZEn = "&&z2l1Pt>7&&"+stdIso("z2l1",0.275,"ele")+"&&z2Charge!=0&&met<20&&z2l2SIP<4";
	TString SEEZt1d  = "&&z2l1Pt>7&&z2Charge!=0&&met<20&&z2l1CiCTight&1==1";
	TString SEEZt2d  = "&&z2l2Pt>7&&z2Charge!=0&&met<20&&z2l2CiCTight&1==1";
	TString SMMZt1d  = "&&z2l1Pt>5&&z2Charge!=0&&met<20";
	TString SMMZt2d  = "&&z2l2Pt>5&&z2Charge!=0&&met<20";
	TString SEMZtEd  = "&&z2l1Pt>7&&z2Charge!=0&&met<20&&z2l1CiCTight&1==1";
	TString SEMZtMd  = "&&z2l2Pt>5&&z2Charge!=0&&met<20&&z2l1CiCTight&1==1";
	TString SMTZn = "&&"+stdIso("z2l1",0.275,"mu")+"&&z2l1Pt>5&&z2Charge!=0&&met<20&&z2l2EleVeto&&z2l2MuVeto&&z2l1SIP<4";
	TString SETZn = "&&z2l1Pt>7&&"+stdIso("z2l1",0.275,"ele")+"&&z2Charge!=0&&z2l2EleVeto&&z2l2MuVeto&&met<20&&z2l1SIP<4";
	TString SMTZd = "&&z2l1Pt>5&&z2Charge!=0&&met<20&&z2l2EleVeto&&z2l2MuVeto";
	TString SETZd = "&&z2l1Pt>7&&z2Charge!=0&&z2l2EleVeto&&z2l2MuVeto&&met<20";
	gROOT->ProcessLine(".!mkdir FitPlots");

	std::cout << LEleZ+SMTZd << std::endl;

	////////////////////////////////Measure Fake Rate for Leptons////////////////////////////////////////////

	e->cd();
	eleEleEleMuEventTree_noIsoSS->cd();
	TGraphAsymmErrors *ee = new TGraphAsymmErrors();
	TGraphAsymmErrors *mm = new TGraphAsymmErrors();
	double DE,NE,DM,NM,NET,NMT,DET,DMT,NEt,NMt; //-t is hack for tighter iso. legs
	TCanvas *C = new TCanvas();
	int nBins=9;
	Float_t xBins[nBins] = {0,10,20,30,40,50,60,70,80};
	TH1F *nm = new TH1F("nm", "nm", nBins-1,xBins);
	TH1F *dm = new TH1F("dm", "dm", nBins-1,xBins);
	TH1F *ne = new TH1F("ne", "ne", nBins-1,xBins);
	TH1F *de = new TH1F("de", "de", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>ne",LEleZ+SEMZEn);
	eventTree->Draw("z2l2Pt>>nm",LEleZ+SEMZMn);
	eventTree->Draw("z2l1Pt>>de",LEleZ+SEMZtEd);
	eventTree->Draw("z2l2Pt>>dm",LEleZ+SEMZtMd);
	NE = eventTree->GetEntries(LEleZ+SEMZEn);
	NEt = eventTree->GetEntries(LEleZ+SEMZEn+"&&"+TString(stdIso("z2l1",0.08,"ele")));
	DE = eventTree->GetEntries(LEleZ+SEMZtEd);
	NM = eventTree->GetEntries(LEleZ+SEMZMn);
	NMt = eventTree->GetEntries(LEleZ+SEMZMn+"&&"+TString(stdIso("z2l2",0.10,"mu")));
	DM = eventTree->GetEntries(LEleZ+SEMZtMd);
	std::cout << "after eeem:" << endl;
	std::cout << "NE: " << NE << endl;
	std::cout << "NEt: " << NEt << endl;
	std::cout << "NM: " << NM << endl;
	std::cout << "NMt: " << NMt << endl;
	std::cout << "DE: " << DE << endl;
	m->cd();
	muMuEleMuEventTree_noIsoSS->cd();
	TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
	TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
	TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
	TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>ne1",LMuZ+SEMZEn);
	eventTree->Draw("z2l2Pt>>nm1",LMuZ+SEMZMn);
	eventTree->Draw("z2l1Pt>>de1",LMuZ+SEMZtEd);
	eventTree->Draw("z2l2Pt>>dm1",LMuZ+SEMZtMd);
	ne->Add(ne,ne1);
	nm->Add(nm,nm1);
	de->Add(de,de1);
	dm->Add(dm,dm1);
	NE += eventTree->GetEntries(LMuZ+SEMZEn);
	NEt = eventTree->GetEntries(LMuZ+SEMZEn+"&&"+TString(stdIso("z2l1",0.08,"ele")));
	DE += eventTree->GetEntries(LMuZ+SEMZtEd);
	NM += eventTree->GetEntries(LMuZ+SEMZMn);
	NMt += eventTree->GetEntries(LMuZ+SEMZMn+"&&"+TString(stdIso("z2l2",0.10,"mu")));
	DM += eventTree->GetEntries(LMuZ+SEMZtMd);
	std::cout << "after mmem:" << endl;
	std::cout << "NE: " << NE << endl;
	std::cout << "NEt: " << NEt << endl;
	std::cout << "NM: " << NM << endl;
	std::cout << "NMt: " << NMt << endl;
	std::cout << "DE: " << DE << endl;
	std::cout << NE/DE << endl;
	std::cout << NEt/DE << endl;
	m->cd();
	muMuMuMuEventTree_noIsoSS->cd();
	TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
	TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
	TH1F *nm2 = new TH1F("nm2", "nm2", nBins-1,xBins);
	TH1F *dm2 = new TH1F("dm2", "dm2", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>nm1",LMuZ+SMMZ1n);
	eventTree->Draw("z2l2Pt>>nm2",LMuZ+SMMZ2n);
	eventTree->Draw("z2l1Pt>>dm1",LMuZ+SMMZt1d);
	eventTree->Draw("z2l2Pt>>dm2",LMuZ+SMMZt2d);
	nm->Add(nm,nm1);
	nm->Add(nm,nm2);
	dm->Add(dm,dm1);
	dm->Add(dm,dm2);
	NM += eventTree->GetEntries(LMuZ+SMMZ1n);
	NMt += eventTree->GetEntries(LMuZ+SMMZ1n+"&&"+TString(stdIso("z2l1",0.10,"mu")));
	NM += eventTree->GetEntries(LMuZ+SMMZ2n);
	NMt += eventTree->GetEntries(LMuZ+SMMZ2n+"&&"+TString(stdIso("z2l2",0.10,"mu")));
	DM += eventTree->GetEntries(LMuZ+SMMZt1d);
	DM += eventTree->GetEntries(LMuZ+SMMZt2d);
	e->cd();
	eleEleMuMuEventTree_noIsoSS->cd();
	TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
	TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
	TH1F *nm2 = new TH1F("nm2", "nm2", nBins-1,xBins);
	TH1F *dm2 = new TH1F("dm2", "dm2", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>nm1",LEleZ+SMMZ1n);
	eventTree->Draw("z2l2Pt>>nm2",LEleZ+SMMZ2n);
	eventTree->Draw("z2l1Pt>>dm1",LEleZ+SMMZt1d);
	eventTree->Draw("z2l2Pt>>dm2",LEleZ+SMMZt2d);
	nm->Add(nm,nm1);
	nm->Add(nm,nm2);
	dm->Add(dm,dm1);
	dm->Add(dm,dm2);
	NM += eventTree->GetEntries(LEleZ+SMMZ1n);
	NMt += eventTree->GetEntries(LEleZ+SMMZ1n+"&&"+TString(stdIso("z2l1",0.10,"mu")));
	NM += eventTree->GetEntries(LEleZ+SMMZ2n);
	NMt += eventTree->GetEntries(LEleZ+SMMZ2n+"&&"+TString(stdIso("z2l2",0.10,"mu")));
	DM += eventTree->GetEntries(LEleZ+SMMZt1d);
	DM += eventTree->GetEntries(LEleZ+SMMZt2d);
	m->cd();
	muMuEleEleEventTree_noIsoSS->cd();
	TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
	TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
	TH1F *ne2 = new TH1F("ne2", "ne2", nBins-1,xBins);
	TH1F *de2 = new TH1F("de2", "de2", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>ne1",LMuZ+SEEZ1n);
	eventTree->Draw("z2l2Pt>>ne2",LMuZ+SEEZ2n);
	eventTree->Draw("z2l1Pt>>de1",LMuZ+SEEZt1d);
	eventTree->Draw("z2l2Pt>>de2",LMuZ+SEEZt2d);
	ne->Add(ne,ne1);
	ne->Add(ne,ne2);
	de->Add(de,de1);
	de->Add(de,de2);
	NE += eventTree->GetEntries(LMuZ+SEEZ1n);
	NEt += eventTree->GetEntries(LMuZ+SEEZ1n+"&&"+TString(stdIso("z2l1",0.08,"ele")));
	NE += eventTree->GetEntries(LMuZ+SEEZ2n);
	NEt += eventTree->GetEntries(LMuZ+SEEZ2n+"&&"+TString(stdIso("z2l2",0.08,"ele")));
	DE += eventTree->GetEntries(LMuZ+SEEZt1d);
	DE += eventTree->GetEntries(LMuZ+SEEZt2d);
	std::cout << "after mmee:" << endl;
	std::cout << "NE: " << NE << endl;
	std::cout << "NEt: " << NEt << endl;
	std::cout << "DE: " << DE << endl;
	std::cout << NE/DE << endl;
	std::cout << NEt/DE << endl;
	e->cd();
	eleEleEleEleEventTree_noIsoSS->cd();
	TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
	TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
	TH1F *ne2 = new TH1F("ne2", "ne2", nBins-1,xBins);
	TH1F *de2 = new TH1F("de2", "de2", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>ne1",LEleZ+SEEZ1n);
	eventTree->Draw("z2l2Pt>>ne2",LEleZ+SEEZ2n);
	eventTree->Draw("z2l1Pt>>de1",LEleZ+SEEZt1d);
	eventTree->Draw("z2l2Pt>>de2",LEleZ+SEEZt2d);
	ne->Add(ne,ne1);
	ne->Add(ne,ne2);
	de->Add(de,de1);
	de->Add(de,de2);
	NE += eventTree->GetEntries(LEleZ+SEEZ1n);
	NE += eventTree->GetEntries(LEleZ+SEEZ2n);
	NEt += eventTree->GetEntries(LEleZ+SEEZ1n+"&&"+TString(stdIso("z2l1",0.08,"ele")));
	NEt += eventTree->GetEntries(LEleZ+SEEZ2n+"&&"+TString(stdIso("z2l2",0.08,"ele")));
	DE += eventTree->GetEntries(LEleZ+SEEZt1d);
	DE += eventTree->GetEntries(LEleZ+SEEZt2d);
	std::cout << "after eeee:" << endl;
	std::cout << "NE: " << NE << endl;
	std::cout << "NEt: " << NEt << endl;
	std::cout << "DE: " << DE << endl;
	std::cout << NE/DE << endl;
	std::cout << NEt/DE << endl;
	e->cd();
	eleEleEleTauEventTree_noIsoSS->cd();
	TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
	TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>ne1",LEleZ+SETZn);
	eventTree->Draw("z2l1Pt>>de1",LEleZ+SETZd);
	ne->Add(ne,ne1);
	de->Add(de,de1);
	NE += eventTree->GetEntries(LEleZ+SETZn);
	NEt += eventTree->GetEntries(LEleZ+SETZn+"&&"+TString(stdIso("z2l1",0.08,"ele")));
	DE += eventTree->GetEntries(LEleZ+SETZd);
	std::cout << "after eeet:" << endl;
	std::cout << "NE: " << NE << endl;
	std::cout << "NEt: " << NEt << endl;
	std::cout << "DE: " << DE << endl;
	std::cout << NE/DE << endl;
	std::cout << NEt/DE << endl;
	m->cd();
	muMuEleTauEventTree_noIsoSS->cd();
	TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
	TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>ne1",LMuZ+SETZn);
	eventTree->Draw("z2l1Pt>>de1",LMuZ+SETZd);
	ne->Add(ne,ne1);
	de->Add(de,de1);
	NE += eventTree->GetEntries(LMuZ+SETZn);
	NEt += eventTree->GetEntries(LMuZ+SETZn+"&&"+TString(stdIso("z2l1",0.08,"ele")));
	DE += eventTree->GetEntries(LMuZ+SETZd);
	std::cout << "after mmet:" << endl;
	std::cout << "NE: " << NE << endl;
	std::cout << "NEt: " << NEt << endl;
	std::cout << "DE: " << DE << endl;
	std::cout << NE/DE << endl;
	std::cout << NEt/DE << endl;
	m->cd();
	muMuMuTauEventTree_noIsoSS->cd();
	TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
	TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>nm1",LMuZ+SMTZn);
	eventTree->Draw("z2l1Pt>>dm1",LMuZ+SMTZd);
	nm->Add(nm,nm1);
	dm->Add(dm,dm1);
	NM += eventTree->GetEntries(LMuZ+SMTZn);
	NMt += eventTree->GetEntries(LMuZ+SMTZn+"&&"+TString(stdIso("z2l1",0.10,"mu")));
	DM += eventTree->GetEntries(LMuZ+SMTZd);
	std::cout << "after mmmt: " << endl;
	std::cout << "NM: " << NM << endl;
	std::cout << "NMt: " << NMt << endl;
	std::cout << "DM: " << DM << endl;
	e->cd();
	eleEleMuTauEventTree_noIsoSS->cd();
	TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
	TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
	eventTree->Draw("z2l1Pt>>nm1",LEleZ+SMTZn);
	eventTree->Draw("z2l1Pt>>dm1",LEleZ+SMTZd);
	nm->Add(nm,nm1);
	dm->Add(dm,dm1);
	NM += eventTree->GetEntries(LEleZ+SMTZn);
	NMt += eventTree->GetEntries(LEleZ+SMTZn+"&&"+TString(stdIso("z2l1",0.10,"mu")));
	DM += eventTree->GetEntries(LEleZ+SMTZd);
	std::cout << "after eemt: " << endl;
	std::cout << "NM: " << NM << endl;
	std::cout << "NMt: " << NMt << endl;
	std::cout << "DM: " << DM << endl;
	IFREleErr = sqrt(NE/(DE*DE)+NE*NE/(DE*DE*DE));
	IFREletErr = sqrt(NEt/(DE*DE)+NEt*NEt/(DE*DE*DE));
	IFRMuErr = sqrt(NM/(DM*DM)+NM*NM/(DM*DM*DM));
	IFRMutErr = sqrt(NMt/(DM*DM)+NMt*NMt/(DM*DM*DM));
	fRstream << "eleFR"<< endl; 
	fRstream << NE/DE << endl;
	fRstream << "eleFRe"<< endl; 
	fRstream << IFREleErr << endl;
	fRstream << "eletFR"<< endl; 
	fRstream << NEt/DE << endl;
	fRstream << "eletFRe"<< endl; 
	fRstream << IFREletErr << endl;
	fRstream << "muFR"<< endl; 
	fRstream << NM/DM << endl;
	fRstream << "muFRe"<< endl; 
	fRstream << IFRMuErr << endl;
	fRstream << "mutFR"<< endl; 
	fRstream << NMt/DM << endl;
	fRstream << "mutFRe"<< endl; 
	fRstream << IFRMutErr << endl;
	std::cout << "********************************" << std::endl;
	std::cout << "eFR:" << NE << "/" << DE << "=" << NE/DE << std::endl;
	std::cout << "eFR (tight):" << NEt << "/" << DE << "=" << NEt/DE << std::endl;
	std::cout << "mFR:" << NM << "/" << DM << "=" << NM/DM << std::endl;
	std::cout << "mFR (tight):" << NMt << "/" << DM << "=" << NMt/DM << std::endl;
	std::cout << "********************************" << std::endl;
	mm->BayesDivide(nm,dm);
	mm->GetXaxis()->SetTitle("#mu p_{T}");
	mm->GetYaxis()->SetRangeUser(0,1.0);
	mm->GetYaxis()->SetTitle("Fake rate");
	mm->Draw("AP");
	C->SaveAs("FitPlots/mu.png");
	ee->BayesDivide(ne,de);
	ee->GetXaxis()->SetTitle("e p_{T}");
	ee->GetYaxis()->SetTitle("Fake rate");
	ee->GetYaxis()->SetRangeUser(0,1.0);
	ee->Draw("AP");
	C->SaveAs("FitPlots/ele.png");
	////////////////////////////////////// Measure fake rate for Taus  ////////////////////////////////////////////////////
	//Two channels combined for increased statistics: EETT, MMTT

	double DTau,NLoose,NMed;
	e->cd();
	eleEleTauTauEventTree_noIsoSS->cd();
	TGraphAsymmErrors *tt = new TGraphAsymmErrors();
	TGraphAsymmErrors *lt = new TGraphAsymmErrors();
	TH1F *n1 = new TH1F("n1", "n1", 18, 10,100);
	TH1F *d1 = new TH1F("d1", "d1", 18, 10,100);
	TH1F *n1VL = new TH1F("n1VL", "n1VL", 18, 10,100);
	TH1F *d1VL = new TH1F("d1VL", "d1VL", 18, 10,100);
	eventTree->Draw("z2l1Pt>>n1",LEleZ+STTZt1n);
	eventTree->Draw("z2l2Pt>>n2(18,10,100)",LEleZ+STTZt2n);
	eventTree->Draw("z2l1Pt>>n1VL",LEleZ+STTZt1nVL);
	eventTree->Draw("z2l2Pt>>n2VL(18,10,100)",LEleZ+STTZt2nVL);
	n1->Add(n1,n2);
	n1VL->Add(n1VL,n2VL);
	NLoose = eventTree->GetEntries(LEleZ+STTZt1nVL+"&&z2l1Pt>20&&z2l2Pt>20");
	NLoose += eventTree->GetEntries(LEleZ+STTZt2nVL+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1LooseIsoCombDB");
	NMed = eventTree->GetEntries(LEleZ+STTZt1n+"&&z2l1Pt>20&&z2l2Pt>20");
	NMed += eventTree->GetEntries(LEleZ+STTZt2n+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1MediumIsoCombDB");
	eventTree->Draw("z2l1Pt>>d1",LEleZ+STTZt1d);
	eventTree->Draw("z2l2Pt>>d2(18,10,100)",LEleZ+STTZt2d);
	eventTree->Draw("z2l1Pt>>d1VL",LEleZ+STTZt1d);
	eventTree->Draw("z2l2Pt>>d2VL(18,10,100)",LEleZ+STTZt2d);
	d1->Add(d1,d2);
	d1VL->Add(d1VL,d2VL);
	DTau = 2*eventTree->GetEntries(LEleZ+STTZt2d+"&&z2l1Pt>20&&z2l2Pt>20");
	m->cd();
	muMuTauTauEventTree_noIsoSS->cd();
	eventTree->Draw("z2l1Pt>>n3(18,10,100)",LMuZ+STTZt1n);
	eventTree->Draw("z2l1Pt>>n3VL(18,10,100)",LMuZ+STTZt1nVL);
	n1->Add(n1,n3);
	n1VL->Add(n1VL,n3VL);
	eventTree->Draw("z2l2Pt>>n4(18,10,100)",LMuZ+STTZt2n);
	eventTree->Draw("z2l2Pt>>n4VL(18,10,100)",LMuZ+STTZt2nVL);
	n1->Add(n1,n4);
	n1VL->Add(n1VL,n4VL);
	eventTree->Draw("z2l1Pt>>d3(18,10,100)",LMuZ+STTZt1d);
	eventTree->Draw("z2l1Pt>>d3VL(18,10,100)",LMuZ+STTZt1d);
	d1->Add(d1,d3);
	d1VL->Add(d1VL,d3VL);
	eventTree->Draw("z2l2Pt>>d4(18,10,100)",LMuZ+STTZt2d);
	eventTree->Draw("z2l2Pt>>d4VL(18,10,100)",LMuZ+STTZt2d);
	d1->Add(d1,d4);
	d1VL->Add(d1VL,d4VL);
	NLoose += eventTree->GetEntries(LMuZ+STTZt1nVL+"&&z2l1Pt>20&&z2l2Pt>20");
	NLoose += eventTree->GetEntries(LMuZ+STTZt2nVL+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1LooseIsoCombDB");
	NMed += eventTree->GetEntries(LMuZ+STTZt1n+"&&z2l1Pt>20&&z2l2Pt>20");
	NMed += eventTree->GetEntries(LMuZ+STTZt2n+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1MediumIsoCombDB");
	DTau += 2*eventTree->GetEntries(LMuZ+STTZt2d+"&&z2l1Pt>20&&z2l2Pt>20");


	//////////////Integral Fake Rate >20/////////////////////
/*
	double IFRL,IFRLErr,IFRM,IFRMErr,IFRET,IFRMT,IFRETErr,IFRMTErr;
	IFRET = NET/DET;
	IFRMT = NMT/DMT;
	IFRL = NLoose/DTau;
	IFRLErr = sqrt(NLoose/(DTau*DTau)+NLoose*NLoose/(DTau*DTau*DTau));
	IFRM = NMed/DTau;
	IFRMErr = sqrt(NMed/(DTau*DTau)+NMed*NMed/(DTau*DTau*DTau));
	m->cd();
	muMuTauTauEventTree_noIsoSS->cd();
	double MMTT = eventTree->GetEntries(LMuZ+STTZcuts);
	std::cout << "mmtt cuts: " << LMuZ+STTZcuts << std::endl;
	std::cout << MMTT << " mmtt events fakeable" << std::endl;
	double MMTTt2 = eventTree->GetEntries(LMuZ+STTZcutsT2);
	double MMTTnt2 = eventTree->GetEntries(LMuZ+STTZcutsnT2);
	std::cout << "IFRM: " << IFRM << istd::endl;
	double mmtt = IFRM*IFRM*MMTT/(1-IFRM*IFRM);
	double mmttt2 = IFRM*1.5*IFRM*MMTTt2/(1-IFRM*1.5*IFRM)+IFRM*IFRM*MMTTnt2/(1-IFRM*IFRM);
	double mmttErr = sqrt(MMTT*IFRM*IFRM*IFRM*IFRM+4*IFRMErr*IFRMErr*MMTT*MMTT*IFRM*IFRM);
	// cout << "Events In Control Region " << MMTT << endl;
	cout << "Background Est. for MMTT = " << mmtt << " +- " << mmttErr << endl;
	cout << "Background Est. for MMTT with t2 scaled = " << mmttt2 << " +- " << mmttErr << "(" << MMTTt2+MMTTnt2 << ") fakeable" << endl;
	e->cd();
	eleEleTauTauEventTree_noIsoSS->cd();
	double EETT = eventTree->GetEntries(LEleZ+STTZcuts);
	double eett = IFRM*IFRM*EETT/(1-IFRM*IFRM);
	double eettErr = sqrt(EETT*IFRM*IFRM*IFRM*IFRM+4*IFRMErr*IFRMErr*EETT*EETT*IFRM*IFRM);
	// cout << "Events In Control Region " << EETT << endl;
	//cout << "Background Est. for EETT = " << eett << " +- " << eettErr << endl;
	e->cd();
	eleEleEleTauEventTree_noIsoSS->cd();
	double EEET = eventTree->GetEntries(LEleZ+SETZcuts);
	double eeet = IFRL*EEET/(1-IFRL);
	double eeetErr = sqrt(IFRL*IFRL*EEET+EEET*EEET*IFRLErr*IFRLErr);
	//cout << "Events In Control Region " << EEET << endl;
	//cout << "Background Est. for EEET = " << eeet << " +- " << eeetErr << endl;
	m->cd();
	muMuEleTauEventTree_noIsoSS->cd();
	double MMET = eventTree->GetEntries(LMuZ+SETZcuts);
	double mmet = IFRL*MMET/(1-IFRL);
	double mmetErr = sqrt(IFRL*IFRL*MMET+MMET*MMET*IFRLErr*IFRLErr);
	//cout << "Events In Control Region " << MMET << endl;
	//cout << "Background Est. for MMET = " << mmet << " +- " << mmetErr << endl;
	m->cd();
	muMuMuTauEventTree_noIsoSS->cd();
	double MMMT = eventTree->GetEntries(LMuZ+SMTZcuts);
	double mmmt = IFRL*MMMT/(1-IFRL);
	double mmmtErr = sqrt(IFRL*IFRL*MMMT+MMMT*MMMT*IFRLErr*IFRLErr);
	// cout << "Events In Control Region " << MMMT << endl;
	// cout << "Background Est. for MMMT = " << mmmt << " +- " << mmmtErr << endl;
	e->cd();
	eleEleMuTauEventTree_noIsoSS->cd();
	double EEMT = eventTree->GetEntries(LEleZ+SMTZcuts);
	double eemt = IFRL*EEMT/(1-IFRL);
	double eemtErr = sqrt(IFRL*IFRL*EEMT+EEMT*EEMT*IFRLErr*IFRLErr);
	// cout << "Events In Control Region " << EEMT << endl;
	// cout << "Background Est. for EEMT = " << eemt << " +- " << eemtErr << endl;
*/


	//////////////Fitting, pt dependant fake rates///////////////////
	tt->BayesDivide(n1,d1);
	tt->GetXaxis()->SetTitle("#tau p_{T} GeV");
	tt->GetYaxis()->SetTitle("Fake Rate");
	tt->Draw("AP");
	TF1 *myfit1 = new TF1("myfit1","[0] + [1]*exp([2]*x)", 15, 100);
	myfit1->SetParameter(0, 0);
	myfit1->SetParameter(1, 0);
	myfit1->SetParameter(2, 0);
	tt->Fit("myfit1","WR");
	//l1=new TLine(15,IFRM,100,IFRM);
	//l1->SetLineColor(38);
	//l1->Draw();
	C->SaveAs("FitPlots/tautau.pdf");
	C->SaveAs("FitPlots/tautau.png");
	C->SaveAs("FitPlots/tautau.C");
	double c0 = myfit1->GetParameter(0);
	double c1 = myfit1->GetParameter(1);
	double c2 = myfit1->GetParameter(2);
	double e0 = myfit1->GetParError(0);
	double e1 = myfit1->GetParError(1);
	double e2 = myfit1->GetParError(2);
	lt->BayesDivide(n1VL,d1VL);
	lt->GetXaxis()->SetTitle("#tau p_{T} GeV");
	lt->GetYaxis()->SetTitle("Fake Rate");
	lt->GetYaxis()->SetRangeUser(0,0.15);
	lt->Draw("AP");
	TF1 *myfit2 = new TF1("myfit2","[0] + [1]*exp([2]*x)", 15, 100);
	myfit2->SetParameter(0, 0);
	myfit2->SetParameter(1, 0);
	myfit2->SetParameter(2, 0);
	lt->Fit("myfit2","WR");
	cout << "Integral Loose Fakerate = " << NLoose << "/" << DTau << " = " << NLoose/DTau  << endl;
	cout << "Integral Medium Fakerate = " << NMed << "/" << DTau << " = " << NMed/DTau  << endl;
	cout << "Full Loose: " << n1VL->Integral() << "/" << d1VL->Integral() << " = " << n1VL->Integral()/d1->Integral() << endl;
	cout << "Full Medium: " << n1->Integral() << "/" << d1->Integral() << " = " << n1->Integral()/d1->Integral() << endl;
	//l2=new TLine(15,IFRL,100,IFRL);
	//l2->SetLineColor(38);
	//l2->Draw();
	C->SaveAs("FitPlots/tautauL.pdf");
	C->SaveAs("FitPlots/tautauL.png");
	C->SaveAs("FitPlots/tautauL.C");
	double c0VL = myfit2->GetParameter(0);
	double c1VL = myfit2->GetParameter(1);
	double c2VL = myfit2->GetParameter(2);
	double e0VL = myfit2->GetParError(0);
	double e1VL = myfit2->GetParError(1);
	double e2VL = myfit2->GetParError(2);
	std::ostringstream S0;
	std::ostringstream S1;
	std::ostringstream S2;
	std::ostringstream E0;
	std::ostringstream E1;
	std::ostringstream E2;
	std::ostringstream S0VL;
	std::ostringstream S1VL;
	std::ostringstream S2VL;
	std::ostringstream E0VL;
	std::ostringstream E1VL;
	std::ostringstream E2VL;
	S0 << c0;
	S1 << c1;
	S2 << c2;
	E0 << e0;
	E1 << e1;
	E2 << e2;
	S0VL << c0VL;
	S1VL << c1VL;
	S2VL << c2VL;
	E0VL << e0VL;
	E1VL << e1VL;
	E2VL << e2VL;
	TString s0 = S0.str();
	TString s1 = S1.str();
	TString s2 = S2.str();
	TString se0 = E0.str();
	TString se1 = E1.str();
	TString se2 = E2.str();
	TString s0VL = S0VL.str();
	TString s1VL = S1VL.str();
	TString s2VL = S2VL.str();
	TString se0VL = E0VL.str();
	TString se1VL = E1VL.str();
	TString se2VL = E2VL.str();
	fRstream << "s0"<< endl; 
	fRstream << s0 << endl;
	fRstream << "s1"<< endl; 
	fRstream << s1 << endl;
	fRstream << "s2"<< endl; 
	fRstream << s2 << endl;
	fRstream << "se0"<< endl; 
	fRstream << se0 << endl;
	fRstream << "se1"<< endl; 
	fRstream << se1 << endl;
	fRstream << "se2"<< endl; 
	fRstream << se2 << endl;
	fRstream << "s0VL"<< endl; 
	fRstream << s0VL << endl;
	fRstream << "s1VL"<< endl; 
	fRstream << s1VL << endl;
	fRstream << "s2VL"<< endl; 
	fRstream << s2VL << endl;
	fRstream << "se0VL"<< endl; 
	fRstream << se0VL << endl;
	fRstream << "se1VL"<< endl; 
	fRstream << se1VL << endl;
	fRstream << "se2VL"<< endl; 
	fRstream << se2VL << endl;
	fRstream.close();
}
