#include "FWCore/Framework/interface/MakerMacros.h"
#include "UWAnalysis/NtupleTools/plugins/JetCountFillerOL.h"

DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuTauTauQuadJetCountFillerOL, "PATMuMuTauTauQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuTauQuadJetCountFillerOL, "PATMuMuMuTauQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleTauQuadJetCountFillerOL, "PATMuMuEleTauQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuMuQuadJetCountFillerOL, "PATMuMuMuMuQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleMuQuadJetCountFillerOL, "PATMuMuEleMuQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleEleQuadJetCountFillerOL, "PATMuMuEleEleQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleTauTauQuadJetCountFillerOL, "PATEleEleTauTauQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuTauQuadJetCountFillerOL, "PATEleEleMuTauQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleTauQuadJetCountFillerOL, "PATEleEleEleTauQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleMuQuadJetCountFillerOL, "PATEleEleEleMuQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuMuQuadJetCountFillerOL, "PATEleEleMuMuQuadJetCountFillerOL");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleEleQuadJetCountFillerOL, "PATEleEleEleEleQuadJetCountFillerOL");


