#include "FWCore/Framework/interface/MakerMacros.h"
#include "UWAnalysis/NtupleTools/plugins/JetCountFiller.h"

DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuTauPairJetCountFiller, "PATMuTauPairJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuJetPairJetCountFiller, "PATMuJetPairJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleTauPairJetCountFiller, "PATEleTauPairJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleMuPairJetCountFiller, "PATEleMuPairJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuPairJetCountFiller, "PATMuPairJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATDiTauPairJetCountFiller, "PATDiTauPairJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuTauTauQuadJetCountFiller, "PATMuMuTauTauQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuTauQuadJetCountFiller, "PATMuMuMuTauQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleTauQuadJetCountFiller, "PATMuMuEleTauQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuMuQuadJetCountFiller, "PATMuMuMuMuQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleMuQuadJetCountFiller, "PATMuMuEleMuQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleEleQuadJetCountFiller, "PATMuMuEleEleQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleTauTauQuadJetCountFiller, "PATEleEleTauTauQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuTauQuadJetCountFiller, "PATEleEleMuTauQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleTauQuadJetCountFiller, "PATEleEleEleTauQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleMuQuadJetCountFiller, "PATEleEleEleMuQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleEleQuadJetCountFiller, "PATEleEleEleEleQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuMuQuadJetCountFiller, "PATEleEleMuMuQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleSCQuadJetCountFiller, "PATEleEleEleSCQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCEleEleQuadJetCountFiller, "PATEleSCEleEleQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleSCQuadJetCountFiller, "PATMuMuEleSCQuadJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCMuMuQuadJetCountFiller, "PATEleSCMuMuQuadJetCountFiller");

DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuTriJetCountFiller, "PATMuMuMuTriJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleTriJetCountFiller, "PATMuMuEleTriJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuTriJetCountFiller, "PATEleEleMuTriJetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleTriJetCountFiller, "PATEleEleEleTriJetCountFiller");


