#include "FWCore/Framework/interface/MakerMacros.h"
#include "UWAnalysis/NtupleTools/plugins/LeptonExtraCountFiller.h"

DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuTauQuadTauExtraCountFiller, "PATMuMuMuTauQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuTauTauQuadTauExtraCountFiller, "PATMuMuTauTauQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleTauQuadTauExtraCountFiller, "PATMuMuEleTauQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleMuQuadTauExtraCountFiller, "PATMuMuEleMuQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleEleQuadTauExtraCountFiller, "PATMuMuEleEleQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuMuQuadTauExtraCountFiller, "PATMuMuMuMuQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuTauQuadTauExtraCountFiller, "PATEleEleMuTauQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleTauTauQuadTauExtraCountFiller, "PATEleEleTauTauQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleTauQuadTauExtraCountFiller, "PATEleEleEleTauQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleMuQuadTauExtraCountFiller, "PATEleEleEleMuQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleEleQuadTauExtraCountFiller, "PATEleEleEleEleQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuMuQuadTauExtraCountFiller, "PATEleEleMuMuQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleSCQuadTauExtraCountFiller, "PATEleEleEleSCQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCEleEleQuadTauExtraCountFiller, "PATEleSCEleEleQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleSCQuadTauExtraCountFiller, "PATMuMuEleSCQuadTauExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCMuMuQuadTauExtraCountFiller, "PATEleSCMuMuQuadTauExtraCountFiller");

DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuTauQuadMuExtraCountFiller, "PATMuMuMuTauQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuTauTauQuadMuExtraCountFiller, "PATMuMuTauTauQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleTauQuadMuExtraCountFiller, "PATMuMuEleTauQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleMuQuadMuExtraCountFiller, "PATMuMuEleMuQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleEleQuadMuExtraCountFiller, "PATMuMuEleEleQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuMuQuadMuExtraCountFiller, "PATMuMuMuMuQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuTauQuadMuExtraCountFiller, "PATEleEleMuTauQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleTauTauQuadMuExtraCountFiller, "PATEleEleTauTauQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleTauQuadMuExtraCountFiller, "PATEleEleEleTauQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleMuQuadMuExtraCountFiller, "PATEleEleEleMuQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleEleQuadMuExtraCountFiller, "PATEleEleEleEleQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuMuQuadMuExtraCountFiller, "PATEleEleMuMuQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleSCQuadMuExtraCountFiller, "PATEleEleEleSCQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCEleEleQuadMuExtraCountFiller, "PATEleSCEleEleQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleSCQuadMuExtraCountFiller, "PATMuMuEleSCQuadMuExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCMuMuQuadMuExtraCountFiller, "PATEleSCMuMuQuadMuExtraCountFiller");

DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuTauQuadEleExtraCountFiller, "PATMuMuMuTauQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuTauTauQuadEleExtraCountFiller, "PATMuMuTauTauQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleTauQuadEleExtraCountFiller, "PATMuMuEleTauQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleMuQuadEleExtraCountFiller, "PATMuMuEleMuQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleEleQuadEleExtraCountFiller, "PATMuMuEleEleQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuMuQuadEleExtraCountFiller, "PATMuMuMuMuQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuTauQuadEleExtraCountFiller, "PATEleEleMuTauQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleTauTauQuadEleExtraCountFiller, "PATEleEleTauTauQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleTauQuadEleExtraCountFiller, "PATEleEleEleTauQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleMuQuadEleExtraCountFiller, "PATEleEleEleMuQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleEleQuadEleExtraCountFiller, "PATEleEleEleEleQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuMuQuadEleExtraCountFiller, "PATEleEleMuMuQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleSCQuadEleExtraCountFiller, "PATEleEleEleSCQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCEleEleQuadEleExtraCountFiller, "PATEleSCEleEleQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleSCQuadEleExtraCountFiller, "PATMuMuEleSCQuadEleExtraCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCMuMuQuadEleExtraCountFiller, "PATEleSCMuMuQuadEleExtraCountFiller");
