#include "FWCore/Framework/interface/MakerMacros.h"
#include "UWAnalysis/NtupleTools/plugins/VBFjetCountFiller.h"

DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuTauTauQuadVBFjetCountFiller, "PATMuMuTauTauQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuTauQuadVBFjetCountFiller, "PATMuMuMuTauQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleTauQuadVBFjetCountFiller, "PATMuMuEleTauQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuMuMuQuadVBFjetCountFiller, "PATMuMuMuMuQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleMuQuadVBFjetCountFiller, "PATMuMuEleMuQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleEleQuadVBFjetCountFiller, "PATMuMuEleEleQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleTauTauQuadVBFjetCountFiller, "PATEleEleTauTauQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuTauQuadVBFjetCountFiller, "PATEleEleMuTauQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleTauQuadVBFjetCountFiller, "PATEleEleEleTauQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleMuQuadVBFjetCountFiller, "PATEleEleEleMuQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleEleQuadVBFjetCountFiller, "PATEleEleEleEleQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleMuMuQuadVBFjetCountFiller, "PATEleEleMuMuQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleEleEleSCQuadVBFjetCountFiller, "PATEleEleEleSCQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCEleEleQuadVBFjetCountFiller, "PATEleSCEleEleQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATMuMuEleSCQuadVBFjetCountFiller, "PATMuMuEleSCQuadVBFjetCountFiller");
DEFINE_EDM_PLUGIN(NtupleFillerFactory, PATEleSCMuMuQuadVBFjetCountFiller, "PATEleSCMuMuQuadVBFjetCountFiller");
