#include "UWAnalysis/RecoTools/interface/SVfitDiTauLikelihoodBase.h"

#include "FWCore/Framework/interface/MakerMacros.h"

EDM_REGISTER_PLUGINFACTORY(SVfitElecTauPairLikelihoodBasePluginFactory, "SVfitElecTauPairLikelihoodBasePluginFactory");
EDM_REGISTER_PLUGINFACTORY(SVfitMuTauPairLikelihoodBasePluginFactory, "SVfitMuTauPairLikelihoodBasePluginFactory");
EDM_REGISTER_PLUGINFACTORY(SVfitDiTauPairLikelihoodBasePluginFactory, "SVfitDiTauPairLikelihoodBasePluginFactory");
EDM_REGISTER_PLUGINFACTORY(SVfitElecMuPairLikelihoodBasePluginFactory, "SVfitElecMuPairLikelihoodBasePluginFactory");
EDM_REGISTER_PLUGINFACTORY(SVfitDiElecPairLikelihoodBasePluginFactory, "SVfitDiElecPairLikelihoodBasePluginFactory");
EDM_REGISTER_PLUGINFACTORY(SVfitMuPairLikelihoodBasePluginFactory, "SVfitMuPairLikelihoodBasePluginFactory");
EDM_REGISTER_PLUGINFACTORY(SVfitMuTrackPairLikelihoodBasePluginFactory, "SVfitMuTrackPairLikelihoodBasePluginFactory");
EDM_REGISTER_PLUGINFACTORY(SVfitEleTrackPairLikelihoodBasePluginFactory, "SVfitEleTrackPairLikelihoodBasePluginFactory");

EDM_REGISTER_PLUGINFACTORY(SVfitDiCandidatePairLikelihoodBasePluginFactory, "SVfitDiCandidatePairLikelihoodBasePluginFactory");
