#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat TP-MC.py >MC2.py
cat CONDOR.py >>MC2.py

#PYTHIA
#farmoutAnalysisJobs  --input-files-per-job=1 --skip-existing-output --output-dir=.  --input-dbs-path=/DYToTauTau_M-20_CT10_TuneZ2_7TeV-powheg-pythia-tauola/Spring11-PU_S1_START311_V1G1-v2/AODSIM  MMTP-ZTT $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/ZMuMuTagAndProbe/MC2.py
#farmoutAnalysisJobs $1 --input-files-per-job=1 --skip-existing-output --output-dir=.  --input-dbs-path=/DYToMuMu_M-20_TuneZ2_7TeV-pythia6/Summer11-PU_S3_START42_V11-v1/AODSIM  ZMM $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/ZMuMuTagAndProbe/MMTP.py
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=.  --input-dbs-path=/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/Spring11-PU_S1_START311_V1G1-v1/AODSIM  MMTP-W $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/ZMuMuTagAndProbe/MC2.py
#farmoutAnalysisJobs --skip-existing-output --input-files-per-job=2 --output-dir=.  --input-dbs-path=/QCD_Pt-20_MuEnrichedPt-15_TuneZ2_7TeV-pythia6/Spring11-PU_S1_START311_V1G1-v1/AODSIM MMTP-QCD $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/ZMuMuTagAndProbe/MC2.py
farmoutAnalysisJobs --skip-existing-output --input-files-per-job=2 --output-dir=. --input-dbs-path=/QCD_Pt-20to30_MuPt5Enriched_TuneZ2_7TeV-pythia6/Summer11-PU_S3_START42_V11-v2/AODSIM TP-QCD20Mu5 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/IsoTagAndProbe/MC2.py
farmoutAnalysisJobs --skip-existing-output --input-files-per-job=2 --output-dir=. --input-dbs-path=/QCD_Pt-15to30_TuneZ2_7TeV_pythia6/Summer11-PU_S3_START42_V11-v2/AODSIM TP-QCD15 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/IsoTagAndProbe/MC2.py
rm MC2.py



