#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat LLLL-MC.py >MC2.py
cat CONDOR.py >>MC2.py

farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-dbs-path=/ZZTo4tau_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ4T $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-dbs-path=/ZZTo4mu_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM	ZZ4M $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-dbs-path=/ZZTo4e_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ4E $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-dbs-path=/ZZTo2mu2tau_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ2M2T $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-dbs-path=/ZZTo2e2tau_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ2E2T $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-dbs-path=/ZZTo2e2mu_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ2E2M $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py

rm MC2.py
