#!/bin/sh
#voms-proxy-init --voms cms --valid 100:00

BG=false
BGSS=false
DATA=false
MC=false
while [ "$1" != "" ]; do
    case $1 in
        --BG )
            shift
            BG=$1
            ;;
        --BGSS )
            shift
            BGSS=$1
            ;;
        --DATA )
            shift
            DATA=$1
            ;;
        --MC )
            shift
            MC=$1
            ;;
        * )
            TAG=$1
    esac
    shift
done

mkdir -p /scratch/$USER/DAGs/$TAG/

if [[ $TAG != "" ]]; then
    postfix="_"$TAG
fi

if [[ $MC == true ]]; then
    cat LLLL-MC.py >MC.py
    cat CONDOR.py >> MC.py

    #ZZ samples
#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ZZ4T_8TeV --input-dbs-path=/ZZTo4tau_8TeV-powheg-pythia6/iross-ZZ4T_powheg_2012-06-08-8TeV-PatTuple-4495432-0651de2bb07022ffcd3866fd2307fdf9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4T_8TeV$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ZZ4E_8TeV --input-dbs-path=/ZZTo4e_8TeV-powheg-pythia6/iross-ZZ4E_powheg_2012-06-08-8TeV-PatTuple-4495432-0651de2bb07022ffcd3866fd2307fdf9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4E_8TeV$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ZZ4M_8TeV --input-dbs-path=/ZZTo4mu_8TeV-powheg-pythia6/iross-ZZ4M_powheg_2012-06-08-8TeV-PatTuple-4495432-0651de2bb07022ffcd3866fd2307fdf9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4M_8TeV$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ZZ2M2T_8TeV --input-dbs-path=/ZZTo2mu2tau_8TeV-powheg-pythia6/iross-ZZ2M2T_powheg_2012-06-08-8TeV-PatTuple-4495432-0651de2bb07022ffcd3866fd2307fdf9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ2M2T_8TeV$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ZZ2E2T_8TeV --input-dbs-path=/ZZTo2e2tau_8TeV-powheg-pythia6/iross-ZZ2E2T_powheg_2012-06-08-8TeV-PatTuple-4495432-0651de2bb07022ffcd3866fd2307fdf9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ2E2T_8TeV$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ZZ2E2M_8TeV --input-dbs-path=/ZZTo2e2mu_8TeV-powheg-pythia6/iross-ZZ2E2M_powheg_2012-06-08-8TeV-PatTuple-4495432-0651de2bb07022ffcd3866fd2307fdf9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ2E2M_8TeV$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py

    farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-dbs-path=/ZZTo4L_TuneZ2star_8TeV_pythia6_tauola/iross-ZZJetsTo4L_pythia_2012-06-05-8TeV-PatTuple-077b195-4a10b6ece30e0bec2ece1a35ded7d8c9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4L_pythia$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
#    farmoutAnalysisJobs --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ZZ4L_pythia --input-dbs-path=/ZZTo4L_TuneZ2star_8TeV_pythia6_tauola/iross-ZZJetsTo4L_pythia_2012-06-05-8TeV-PatTuple-077b195-4a10b6ece30e0bec2ece1a35ded7d8c9/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4L_pythia$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py

    #BG samples
#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DYJets50 --input-dbs-path=/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball/swanson-Zjets_M50_2012-06-02-8TeV-078e4bc-ea74c25a04048a8dd7df6542c03c7a9b/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DYJets50$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py

#    farmoutAnalysisJobs  --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/ggH125 --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/GluGluToHToZZTo4L_M-125_8TeV-powheg-pythia6  --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ggH125$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
    rm MC.py
fi

if [[ $DATA == true ]]; then
    cat LLLL.py > DATA.py
    cat CONDOR.py >> DATA.py

    #data
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleMu2012A --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012A_PromptReco_v1_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012A$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleMu2012B --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012B_PromptReco_v1_a_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012B$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py

    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleElectron2012A --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012A_PromptReco_v1_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012A$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleElectron2012B --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012B_PromptReco_v1_a_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012B$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py
    rm DATA.py
fi

if [[ $BG = true ]] ; then
    cat LLLL-BG.py > BG.py
    cat CONDOR.py >> BG.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleMu2012A_BG --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012A_PromptReco_v1_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012A_BG$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleMu2012B_BG --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012B_PromptReco_v1_a_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012B_BG$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py

    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleElectron2012A_BG --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012A_PromptReco_v1_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012A_BG$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleElectron2012B_BG --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012B_PromptReco_v1_a_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012B_BG$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py
    rm BG.py
fi

if [[ $BGSS = true ]] ; then
    cat LLLL-BGSS.py > BGSS.py
    cat CONDOR.py >> BGSS.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleMu2012A_BGSS --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012A_PromptReco_v1_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012A_BGSS$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGSS.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleMu2012B_BGSS --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012B_PromptReco_v1_a_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012B_BGSS$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGSS.py

    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleElectron2012A_BGSS --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012A_PromptReco_v1_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012A_BGSS$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGSS.py
    farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$TAG/DoubleElectron2012B_BGSS --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012B_PromptReco_v1_a_2012-06-08-8TeV-PatTuple-data-4495432-c7a1c2223886075833473549ad1960ce/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012B_BGSS$postfix $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGSS.py
    rm BGSS.py
fi

