#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat LLLL-StdIso-BG.py >BGStdIso.py
cat CONDOR.py >>BGStdIso.py

mkdir -p /scratch/$USER/DAGs/$1/

farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Oct03_skim/ --output-dag-file=/scratch/iross/DAGs/$1/MM_Oct03_BGStdIso.dag MM_Oct03_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Jul05_skim/ --output-dag-file=/scratch/iross/DAGs/$1/MM_Jul05_BGStdIso.dag MM_Jul05_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Aug05_skim/ --output-dag-file=/scratch/iross/DAGs/$1/MM_Aug05_BGStdIso.dag MM_Aug05_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_2011Bv1_skim/ --output-dag-file=/scratch/iross/DAGs/$1/MM_2011Bv1_BGStdIso.dag MM_2011Bv1_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Oct03_skim/ --output-dag-file=/scratch/iross/DAGs/$1/EE_Oct03_BGStdIsoOSG.dag EE_Oct03_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Jul05_skim/ --output-dag-file=/scratch/iross/DAGs/$1/EE_Jul05_BGStdIsoOSG.dag EE_Jul05_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Aug05_skim/ --output-dag-file=/scratch/iross/DAGs/$1/EE_Aug05_BGStdIsoOSG.dag EE_Aug05_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_2011Bv1_skim/ --output-dag-file=/scratch/iross/DAGs/$1/EE_2011Bv1_BGStdIsoOSG.dag EE_2011Bv1_BG $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BGStdIso.py

rm BGStdIso.py
