#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat EELL-StdIso.py >EEDATA.py
cat CONDOR.py >>EEDATA.py

cat MMLL-StdIso.py >MMDATA.py
cat CONDOR.py >>MMDATA.py

#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Oct03_skim/ --output-dag-file=/scratch/iross/DAGs/MM_Oct03_Data.dag MM_Oct03 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MMDATA.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Jul05_skim/ --output-dag-file=/scratch/iross/DAGs/MM_Jul05_Data.dag MM_Jul05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MMDATA.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Aug05_skim/ --output-dag-file=/scratch/iross/DAGs/MM_Aug05_Data.dag MM_Aug05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MMDATA.py 
farmoutAnalysisJobs --lumi-mask=dummy.json --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_2011Bv1_skim/ --output-dir=.  --output-dag-file=/scratch/iross/DAGs/MM_2011Bv1_Data.dag MM_2011Bv1_test $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MMDATA.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Oct03_skim/ --output-dag-file=/scratch/iross/DAGs/EE_Oct03_Data.dag EE_Oct03 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/EEDATA.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Jul05_skim/ --output-dag-file=/scratch/iross/DAGs/EE_Jul05_Data.dag EE_Jul05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/EEDATA.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Aug05_skim/ --output-dag-file=/scratch/iross/DAGs/EE_Aug05_Data.dag EE_Aug05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/EEDATA.py 
farmoutAnalysisJobs --lumi-mask=dummy.json --input-files-per-job=2 --skip-existing-output --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_2011Bv1_skim/ --ouptut-dir=. --output-dag-file=/scratch/iross/DAGs/EE_2011Bv1_Data.dag EE_2011Bv1_test $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/EEDATA.py

rm EEDATA.py
rm MMDATA.py
