#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat LLLL-StdIso-MC.py >MC2.py
cat CONDOR.py >>MC2.py

mkdir -p /scratch/$USER/DAGs/$1/

farmoutAnalysisJobs --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$1/ZZ4M.dag --input-dbs-path=/ZZTo4mu_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZZ4M $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$1/ZZ4E.dag --input-dbs-path=/ZZTo4e_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZZ4E $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$1/ZZ4T.dag --input-dbs-path=/ZZTo4tau_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZZ4T $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$1/ZZ2E2M.dag --input-dbs-path=/ZZTo2e2mu_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZZ2E2M $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$1/ZZ2E2T.dag --input-dbs-path=/ZZTo2e2tau_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZZ2E2T $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
farmoutAnalysisJobs --skip-existing-output --output-dir=. --output-dag-file=/scratch/iross/DAGs/$1/ZZ2M2T.dag --input-dbs-path=/ZZTo2mu2tau_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZZ2M2T $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/ZZTo4L_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ4L_stdIso $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/ZZJetsTo4L_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM ZZ4L $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-files-per-job=2 --input-dbs-path=/WZJetsTo3LNu_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  WZ3LM_stdIso $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-files-per-job=2 --input-dbs-path=/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM DYJets_stdIso $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/DYJetsToLL_M-10To50_TuneZ2_7TeV-madgraph/Fall11-PU_S6_START42_V14B-v1/AODSIM DYJets_20-50 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/Z2Jets_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM Z2J $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/GluGluToZZTo4L_7TeV-gg2zz-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM ggZZ4L $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/GluGluToZZTo2L2L_7TeV-gg2zz-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM ggZZ2L2L $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/DYToEE_M-20_TuneZ2_7TeV-pythia6/Fall11-PU_S3_START42_V14B-v2/AODSIM DYEE $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/DYToMuMu_M-20_TuneZ2_7TeV-pythia6/Fall11-PU_S3_START42_V14B-v2/AODSIM DYMuMu $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/TTJets_TuneZ2_7TeV-madgraph-tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM TOP $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=. --input-files-per-job=2 --input-dbs-path=/TTTo2L2Nu2B_7TeV-powheg-pythia6/Fall11-PU_S6_START42_V14B-v1/AODSIM TT2L2nu2B_stdIso $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/ZbbToLL_M-50_TuneZ2_7TeV-madgraph-pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  ZBB $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
#farmoutAnalysisJobs --skip-existing-output --output-dir=.  --input-dbs-path=/WZTo3LNu_TuneZ2_7TeV_pythia6_tauola/Fall11-PU_S6_START42_V14B-v1/AODSIM  WZ3L $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC2.py
rm MC2.py
