#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat LLLL-BG.py >BG.py
cat CONDOR.py >>BG.py

#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Oct03_skim/ --output-dag-file=/scratch/iross/DAGs/MM_Oct03_BG.dag MM_Oct03 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Jul05_skim/ --output-dag-file=/scratch/iross/DAGs/DAGs/MM_Jul05_BG.dag MM_Jul05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_Aug05_skim/ --output-dag-file=/scratch/iross/DAGs/MM_Aug05_BG.dag MM_Aug05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py 
#farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/MM_2011Bv1_skim/ --output-dag-file=/scratch/iross/DAGs/MM_2011Bv1_BG.dag MM_2011Bv1 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Oct03_skim/ --output-dag-file=/scratch/iross/DAGs/EE_Oct03_BG.dag EE_Oct03 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Jul05_skim/ --output-dag-file=/scratch/iross/DAGs/EE_Jul05_BG.dag EE_Jul05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_Aug05_skim/ --output-dag-file=/scratch/iross/DAGs/EE_Aug05_BG.dag EE_Aug05 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py 
farmoutAnalysisJobs --input-files-per-job=2 --skip-existing-output --output-dir=. --input-dir=root://cmsxrootd.hep.wisc.edu//store/user/iross/EE_2011Bv1_skim/ --output-dag-file=/scratch/iross/DAGs/EE_2011Bv1_BG.dag EE_2011Bv1 $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/BG.py

rm BG.py
