#!/bin/sh
voms-proxy-init --voms cms --valid 100:00

cat LLLL-MC.py >MC.py
cat CONDOR.py >>MC.py

cat LLLL.py > DATA.py
cat CONDOR.py >> DATA.py

#ZZ samples
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/ZZTo4tau_8TeV-powheg-pythia6/iross-ZZ4T_powheg_2012-05-29-8TeV-PatTuple-v2-67c1f94-c8fc7c2ff4112a438286838f75d59cdb/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4T_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/ZZTo4e-powheg-pythia6/iross-ZZ4E_powheg_2012-05-29-8TeV-PatTuple-v2-67c1f94-c8fc7c2ff4112a438286838f75d59cdb/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4E_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/ZZTo4mu-powheg-pythia6/iross-ZZ4M_powheg_2012-05-29-8TeV-PatTuple-v2-67c1f94-c8fc7c2ff4112a438286838f75d59cdb/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ4M_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/ZZTo2mu2tau-powheg-pythia6/iross-ZZ2M2T_powheg_2012-05-29-8TeV-PatTuple-v2-67c1f94-c8fc7c2ff4112a438286838f75d59cdb/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ2M2T_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/ZZTo2mu2tau-powheg-pythia6/iross-ZZ2E2T_powheg_2012-05-29-8TeV-PatTuple-v2-67c1f94-c8fc7c2ff4112a438286838f75d59cdb/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet ZZ2E2T_8TeV $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/MC.py
# not in existence: 2E2M, ggZZ samples IAR 03.Jun.2012

#data
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012A_PromptReco_v1_2012-05-29-8TeV-PatTuple-67c1f94-a7f10efca7dd683ad59c7e946715fa59/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012A $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/DoubleMu/iross-data_DoubleMu_Run2012B_PromptReco_v1_a_2012-05-29-8TeV-PatTuple-67c1f94-a7f10efca7dd683ad59c7e946715fa59/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleMu2012B $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py

farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012A_PromptReco_v1_2012-05-29-8TeV-PatTuple-67c1f94-a7f10efca7dd683ad59c7e946715fa59/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012A $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py
farmoutAnalysisjobs --skip-exiting-output --output-dir=. --input-dbs-path=/DoubleElectron/iross-data_DoubleElectron_Run2012B_PromptReco_v1_a_2012-05-29-8TeV-PatTuple-67c1f94-a7f10efca7dd683ad59c7e946715fa59/USER --dbs-service-url=http://cmsdbsprod.cern.ch/cms_dbs_ph_analysis_01/servlet/DBSServlet DoubleElectron2012B $CMSSW_BASE $CMSSW_BASE/src/UWAnalysis/CRAB/LLLL/DATA.py

rm MC.py
rm DATA.py
