#!/bin/sh
OSLSMTMethodAll treeName='eleTauEventTree/eventTree' preselection='HLT_Any&&vertices>0&&diLeptons==0&&lPfRelIsoDeltaBeta<0.1&&tauAbsIsoRho<2.&&tauElectronVeto&&abs(eta1)<2.1'       oshighselection='pZeta<-40&&charge==0'	       oslowselection='pZeta>-20&&charge==0'         sshighselection='pZeta<-40&&charge!=0'	      sslowselection='pZeta>-20&&charge!=0'   	qcdfactor=1.06 qcdfactorErr=0.09  vvHigh=11.952 vvLow=7.41 vvErr=0.4    wFactor=0.4971 wFactorErr=0.009         zjft=111.68 zjfterr=0.1         zmft=393 zmfterr=0.07   ttbarHigh=32.71 ttbarLow=34.53 ttBarErr=0.12 	

