{
gROOT->ProcessLine(".L UWAnalysis/ROOT/interactive/tdrstyle.C");
gROOT->Reset();
setTDRStyle();
//	setStyle();
TFile *e = new TFile("sandbox/zz-latest/DATA.root");
TFile *m = new TFile("sandbox/zz-latest/DATA.root");
TString LEleZ = "dZ12<0.10&&dZ13<0.10&&dZ14<0.10&&HLT_Any&&z1Mass>60&&z1Mass<120&&z1l1CiCTight&1==1&&z1l2CiCTight&1==1&&z1l1MissHits<2&&z1l2MissHits<2&&z1l1RelPFIsoDB<0.25&&z1l2RelPFIsoDB<0.25&&z1l1Pt>20&&z1l2Pt>10";
TString LMuZ = "dZ12<0.10&&dZ13<0.10&&dZ14<0.10&&HLT_Any&&z1Mass>60&&z1Mass<120&&z1l1RelPFIsoDB<0.25&&z1l2RelPFIsoDB<0.25&&z1l1Pt>20&&z1l2Pt>10";

TString STTZt1n = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1MediumIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
TString STTZt2n = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l2MediumIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
TString STTZt1nVL = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1LooseIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
TString STTZt2nVL = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l2LooseIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
TString STTZt1d  = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";
TString STTZt2d  = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1EleVeto&&z2l2EleVeto&&z2l1MuVeto&&z2l2MuVeto&&z2Charge!=0";

TString SEEZ2n = "&&z2l2Pt>7&&z2Charge!=0&&z2l2CiCTight&1==1&&z2l2MissHits<2&&z2l2RelPFIsoDB<0.25&&met<20";
TString SEEZ1n = "&&z2l1Pt>7&&z2Charge!=0&&z2l1CiCTight&1==1&&z2l1MissHits<2&&z2l1RelPFIsoDB<0.25&&met<20";
TString SMMZ2n = "&&z2l2Pt>5&&z2Charge!=0&&z2l2RelPFIsoDB<0.25&&met<20";
TString SMMZ1n = "&&z2l1Pt>5&&z2Charge!=0&&z2l1RelPFIsoDB<0.25&&met<20";
TString SEMZMn = "&&z2l2Pt>5&&z2l2RelPFIsoDB<0.25&&z2Charge!=0&&met<20";
TString SEMZEn = "&&z2l1Pt>5&&z2l1CiCTight&1==1&&z2l1MissHits<2&&z2l1RelPFIsoDB<0.25&&z2Charge!=0&&met<20";
TString SEEZt1d  = "&&z2l1Pt>7&&z2Charge!=0&&met<20";
TString SEEZt2d  = "&&z2l2Pt>7&&z2Charge!=0&&met<20";
TString SMMZt1d  = "&&z2l1Pt>5&&z2Charge!=0&&met<20";
TString SMMZt2d  = "&&z2l2Pt>5&&z2Charge!=0&&met<20";
TString SEMZtEd  = "&&z2l1Pt>7&&z2Charge!=0&&met<20";
TString SEMZtMd  = "&&z2l2Pt>5&&z2Charge!=0&&met<20";
TString SMTZn = "&&z2l1RelPFIsoDB<0.25&&z2l1Pt>10&&z2Charge!=0&&met<20";
TString SETZn = "&&z2l1CiCTight&1==1&&z2l1Pt>10&&z2l1RelPFIsoDB<0.25&&z2l1MissHits<2&&z2Charge!=0&&met<20";
TString SMTZd = "&&z2l1Pt>10&&z2Charge!=0&&met<20";
TString SETZd = "&&z2l1Pt>10&&z2Charge!=0&&met<20";

TString SEEZcuts = "&&z2l1Pt>7&&z2l2Pt>7&&z2Charge==0&&z2l1RelPFIsoDB>0.25&&z2l2RelPFIsoDB>0.25&&z2l1CiCTight&1==1&&z2l2CiCTight&1==1&&z2Mass>60&&z2Mass<120";
TString SMMZcuts = "&&z2l1Pt>5&&z2l2Pt>5&&z2Charge==0&&z2l2RelPFIsoDB>0.25&&z2l1RelPFIsoDB>0.25&&z2Mass>60&&z2Mass<120";
TString SEMZcuts = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1MissHits<2&&z2Charge==0&&z2l1RelPFIsoDB>0.25&&z2l2RelPFIsoDB>0.25&&z2Mass<90";
TString STTZcuts = "&&z2l1Pt>20&&z2l2Pt>20&&z2l1EleVeto&&z2l2EleVeto&&!z2l1MediumIsoCombDB&&!z2l2MediumIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge==0&&z2Mass>30&&z2Mass<80";
TString SMTZcuts = "&&z2l2EleVeto&&!z2l2LooseIsoCombDB&&z2l2MuVetoTight&&z2l1RelPFIsoDB<0.15&&z2l2Pt>20&&z2l1Pt>10&&z2Charge==0&&z2Mass>30&&z2Mass<80";
TString SETZcuts = "&&z2l2EleVeto&&z2l1CiCTight&1==1&&!z2l2LooseIsoCombDB&&z2l2Pt>20&&z2l1Pt>10&&z2l1RelPFIsoDB<0.10&&z2l1MissHits==0&&z2l2MuVeto&&z2Charge==0&&z2Mass>30&&z2Mass<80";
TString STTZcutsT2 = "&&z2l1Pt>20&&z2l2Pt>20&&z2l1EleVeto&&z2l2EleVeto&&!z2l1MediumIsoCombDB&&!z2l2MediumIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge==0&&z2Mass>30&&z2Mass<80&&z2l2Pt>20&&z2l2Pt<30";
TString STTZcutsnT2 ="&&z2l1Pt>20&&z2l2Pt>20&&z2l1EleVeto&&z2l2EleVeto&&!z2l1MediumIsoCombDB&&!z2l2MediumIsoCombDB&&z2l1MuVeto&&z2l2MuVeto&&z2Charge==0&&z2Mass>30&&z2Mass<80&&!(z2l2Pt>20&&z2l2Pt<30)";
gROOT->ProcessLine(".!mkdir FitPlots");

////////////////////////////////Measure Fake Rate for Leptons////////////////////////////////////////////

e->cd();
eleEleEleMuEventTreeID->cd();
TGraphAsymmErrors *ee = new TGraphAsymmErrors();
TGraphAsymmErrors *mm = new TGraphAsymmErrors();
double DE,NE,DM,NM,NET,NMT,DET,DMT;
TCanvas *C = new TCanvas();
int nBins=12;
Float_t xBins[nBins] = {0,5,10,15,17,19,20,30,40,50,70,100};
TH1F *nm = new TH1F("nm", "nm", nBins-1,xBins);
TH1F *dm = new TH1F("dm", "dm", nBins-1,xBins);
TH1F *ne = new TH1F("ne", "ne", nBins-1,xBins);
TH1F *de = new TH1F("de", "de", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>ne",LEleZ+SEMZEn);
eventTree->Draw("z2l2Pt>>nm",LEleZ+SEMZMn);
eventTree->Draw("z2l1Pt>>de",LEleZ+SEMZtEd);
eventTree->Draw("z2l2Pt>>dm",LEleZ+SEMZtMd);
NE = eventTree->GetEntries(LEleZ+SEMZEn);
DE = eventTree->GetEntries(LEleZ+SEMZtEd);
NM = eventTree->GetEntries(LEleZ+SEMZMn);
DM = eventTree->GetEntries(LEleZ+SEMZtMd);
m->cd();
muMuEleMuEventTreeID->cd();
TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>ne1",LMuZ+SEMZEn);
eventTree->Draw("z2l2Pt>>nm1",LMuZ+SEMZMn);
eventTree->Draw("z2l1Pt>>de1",LMuZ+SEMZtEd);
eventTree->Draw("z2l2Pt>>dm1",LMuZ+SEMZtMd);
ne->Add(ne,ne1);
nm->Add(nm,nm1);
de->Add(de,de1);
dm->Add(dm,dm1);
NE += eventTree->GetEntries(LMuZ+SEMZEn);
DE += eventTree->GetEntries(LMuZ+SEMZtEd);
NM += eventTree->GetEntries(LMuZ+SEMZMn);
DM += eventTree->GetEntries(LMuZ+SEMZtMd);
m->cd();
muMuMuMuEventTreeID->cd();
TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
TH1F *nm2 = new TH1F("nm2", "nm2", nBins-1,xBins);
TH1F *dm2 = new TH1F("dm2", "dm2", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>nm1",LMuZ+SMMZ1n);
eventTree->Draw("z2l2Pt>>nm2",LMuZ+SMMZ2n);
eventTree->Draw("z2l1Pt>>dm1",LMuZ+SMMZt1d);
eventTree->Draw("z2l2Pt>>dm2",LMuZ+SMMZt2d);
nm->Add(nm,nm1);
nm->Add(nm,nm2);
dm->Add(dm,dm1);
dm->Add(dm,dm2);
NM += eventTree->GetEntries(LMuZ+SMMZ1n);
NM += eventTree->GetEntries(LMuZ+SMMZ2n);
DM += eventTree->GetEntries(LMuZ+SMMZt1d);
DM += eventTree->GetEntries(LMuZ+SMMZt2d);
e->cd();
eleEleMuMuEventTreeID->cd();
TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
TH1F *nm2 = new TH1F("nm2", "nm2", nBins-1,xBins);
TH1F *dm2 = new TH1F("dm2", "dm2", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>nm1",LEleZ+SMMZ1n);
eventTree->Draw("z2l2Pt>>nm2",LEleZ+SMMZ2n);
eventTree->Draw("z2l1Pt>>dm1",LEleZ+SMMZt1d);
eventTree->Draw("z2l2Pt>>dm2",LEleZ+SMMZt2d);
nm->Add(nm,nm1);
nm->Add(nm,nm2);
dm->Add(dm,dm1);
dm->Add(dm,dm2);
NM += eventTree->GetEntries(LEleZ+SMMZ1n);
NM += eventTree->GetEntries(LEleZ+SMMZ2n);
DM += eventTree->GetEntries(LEleZ+SMMZt1d);
DM += eventTree->GetEntries(LEleZ+SMMZt2d);
m->cd();
muMuEleEleEventTreeID->cd();
TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
TH1F *ne2 = new TH1F("ne2", "ne2", nBins-1,xBins);
TH1F *de2 = new TH1F("de2", "de2", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>ne1",LMuZ+SEEZ1n);
eventTree->Draw("z2l2Pt>>ne2",LMuZ+SEEZ2n);
eventTree->Draw("z2l1Pt>>de1",LMuZ+SEEZt1d);
eventTree->Draw("z2l2Pt>>de2",LMuZ+SEEZt2d);
ne->Add(ne,ne1);
ne->Add(ne,ne2);
de->Add(de,de1);
de->Add(de,de2);
NE += eventTree->GetEntries(LMuZ+SEEZ1n);
NE += eventTree->GetEntries(LMuZ+SEEZ2n);
DE += eventTree->GetEntries(LMuZ+SEEZt1d);
DE += eventTree->GetEntries(LMuZ+SEEZt2d);
e->cd();
eleEleEleEleEventTreeID->cd();
TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
TH1F *ne2 = new TH1F("ne2", "ne2", nBins-1,xBins);
TH1F *de2 = new TH1F("de2", "de2", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>ne1",LEleZ+SEEZ1n);
eventTree->Draw("z2l2Pt>>ne2",LEleZ+SEEZ2n);
eventTree->Draw("z2l1Pt>>de1",LEleZ+SEEZt1d);
eventTree->Draw("z2l2Pt>>de2",LEleZ+SEEZt2d);
ne->Add(ne,ne1);
ne->Add(ne,ne2);
de->Add(de,de1);
de->Add(de,de2);
NE += eventTree->GetEntries(LEleZ+SEEZ1n);
NE += eventTree->GetEntries(LEleZ+SEEZ2n);
DE += eventTree->GetEntries(LEleZ+SEEZt1d);
DE += eventTree->GetEntries(LEleZ+SEEZt2d);
e->cd();
eleEleEleTauEventTreeID->cd();
TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>ne1",LEleZ+SETZn);
eventTree->Draw("z2l1Pt>>de1",LEleZ+SETZd);
ne->Add(ne,ne1);
de->Add(de,de1);
NE += eventTree->GetEntries(LEleZ+SETZn);
DE += eventTree->GetEntries(LEleZ+SETZd);
m->cd();
muMuEleTauEventTreeID->cd();
TH1F *ne1 = new TH1F("ne1", "ne1", nBins-1,xBins);
TH1F *de1 = new TH1F("de1", "de1", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>ne1",LMuZ+SETZn);
eventTree->Draw("z2l1Pt>>de1",LMuZ+SETZd);
ne->Add(ne,ne1);
de->Add(de,de1);
NE += eventTree->GetEntries(LMuZ+SETZn);
DE += eventTree->GetEntries(LMuZ+SETZd);
m->cd();
muMuMuTauEventTreeID->cd();
TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>nm1",LMuZ+SMTZn);
eventTree->Draw("z2l1Pt>>dm1",LMuZ+SMTZd);
nm->Add(nm,nm1);
dm->Add(dm,dm1);
NM += eventTree->GetEntries(LMuZ+SMTZn);
DM += eventTree->GetEntries(LMuZ+SMTZd);
e->cd();
eleEleMuTauEventTreeID->cd();
TH1F *nm1 = new TH1F("nm1", "nm1", nBins-1,xBins);
TH1F *dm1 = new TH1F("dm1", "dm1", nBins-1,xBins);
eventTree->Draw("z2l1Pt>>nm1",LEleZ+SMTZn);
eventTree->Draw("z2l1Pt>>dm1",LEleZ+SMTZd);
nm->Add(nm,nm1);
dm->Add(dm,dm1);
NM += eventTree->GetEntries(LEleZ+SMTZn);
DM += eventTree->GetEntries(LEleZ+SMTZd);


////////////////////////////////////// Measure fake rate for Taus  ////////////////////////////////////////////////////
//Two channels combined for increased statistics: EETT, MMTT

double DTau,NLoose,NMed;
e->cd();
eleEleTauTauEventTreeID->cd();
TGraphAsymmErrors *tt = new TGraphAsymmErrors();
TGraphAsymmErrors *lt = new TGraphAsymmErrors();
TH1F *n1 = new TH1F("n1", "n1", 18, 10,100);
TH1F *d1 = new TH1F("d1", "d1", 18, 10,100);
TH1F *n1VL = new TH1F("n1VL", "n1VL", 18, 10,100);
TH1F *d1VL = new TH1F("d1VL", "d1VL", 18, 10,100);
eventTree->Draw("z2l1Pt>>n1",LEleZ+STTZt1n);
eventTree->Draw("z2l2Pt>>n2(18,10,100)",LEleZ+STTZt2n);
eventTree->Draw("z2l1Pt>>n1VL",LEleZ+STTZt1nVL);
eventTree->Draw("z2l2Pt>>n2VL(18,10,100)",LEleZ+STTZt2nVL);
n1->Add(n1,n2);
n1VL->Add(n1VL,n2VL);
NLoose = eventTree->GetEntries(LEleZ+STTZt1nVL+"&&z2l1Pt>20&&z2l2Pt>20&&z2l1Pt<60&&z2l2Pt<60");
NLoose += eventTree->GetEntries(LEleZ+STTZt2nVL+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1LooseIsoCombDB&&z2l1Pt<60&&z2l2Pt<60");
NMed = eventTree->GetEntries(LEleZ+STTZt1n+"&&z2l1Pt>20&&z2l2Pt>20&&z2l1Pt<60&&z2l2Pt<60");
NMed += eventTree->GetEntries(LEleZ+STTZt2n+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1MediumIsoCombDB&&z2l1Pt<60&&z2l2Pt<60");
eventTree->Draw("z2l1Pt>>d1",LEleZ+STTZt1d);
eventTree->Draw("z2l2Pt>>d2(18,10,100)",LEleZ+STTZt2d);
eventTree->Draw("z2l1Pt>>d1VL",LEleZ+STTZt1d);
eventTree->Draw("z2l2Pt>>d2VL(18,10,100)",LEleZ+STTZt2d);
d1->Add(d1,d2);
d1VL->Add(d1VL,d2VL);
DTau = 2*eventTree->GetEntries(LEleZ+STTZt2d+"&&z2l1Pt>20&&z2l2Pt>20&&z2l1Pt<60&&z2l2Pt<60");
m->cd();
muMuTauTauEventTreeID->cd();
eventTree->Draw("z2l1Pt>>n3(18,10,100)",LMuZ+STTZt1n);
eventTree->Draw("z2l1Pt>>n3VL(18,10,100)",LMuZ+STTZt1nVL);
n1->Add(n1,n3);
n1VL->Add(n1VL,n3VL);
eventTree->Draw("z2l2Pt>>n4(18,10,100)",LMuZ+STTZt2n);
eventTree->Draw("z2l2Pt>>n4VL(18,10,100)",LMuZ+STTZt2nVL);
n1->Add(n1,n4);
n1VL->Add(n1VL,n4VL);
eventTree->Draw("z2l1Pt>>d3(18,10,100)",LMuZ+STTZt1d);
eventTree->Draw("z2l1Pt>>d3VL(18,10,100)",LMuZ+STTZt1d);
d1->Add(d1,d3);
d1VL->Add(d1VL,d3VL);
eventTree->Draw("z2l2Pt>>d4(18,10,100)",LMuZ+STTZt2d);
eventTree->Draw("z2l2Pt>>d4VL(18,10,100)",LMuZ+STTZt2d);
d1->Add(d1,d4);
d1VL->Add(d1VL,d4VL);
NLoose += eventTree->GetEntries(LMuZ+STTZt1nVL+"&&z2l1Pt>20&&z2l2Pt>20&&z2l1Pt<60&&z2l2Pt<60");
NLoose += eventTree->GetEntries(LMuZ+STTZt2nVL+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1LooseIsoCombDB&&z2l1Pt<60&&z2l2Pt<60");
NMed += eventTree->GetEntries(LMuZ+STTZt1n+"&&z2l1Pt>20&&z2l2Pt>20&&z2l1Pt<60&&z2l2Pt<60");
NMed += eventTree->GetEntries(LMuZ+STTZt2n+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1MediumIsoCombDB&&z2l1Pt<60&&z2l2Pt<60");
DTau += 2*eventTree->GetEntries(LMuZ+STTZt2d+"&&z2l1Pt>20&&z2l2Pt>20&&z2l1Pt<60&&z2l2Pt<60");


//////////////Integral Fake Rate >20/////////////////////

double IFRL,IFRLErr,IFRM,IFRMErr,IFRET,IFRMT,IFRETErr,IFRMTErr;
 IFRET = NET/DET;
 IFRMT = NMT/DMT;
 IFRL = NLoose/DTau;
 IFRLErr = sqrt(NLoose/(DTau*DTau)+NLoose*NLoose/(DTau*DTau*DTau));
 IFRM = NMed/DTau;
 IFRMErr = sqrt(NMed/(DTau*DTau)+NMed*NMed/(DTau*DTau*DTau));
 cout << "Integral Loose Fakerate = " << IFRL << "(" << NLoose << "/" << DTau << ") +- " << IFRLErr << endl;
 cout << "Integral Medium Fakerate = " << IFRM << "(" << NMed << "/" << DTau << ") +- " << IFRMErr << endl;
 
 m->cd();
 muMuTauTauEventTreeID->cd();
 double MMTT = eventTree->GetEntries(LMuZ+STTZcuts);
 std::cout << "mmtt cuts: " << LMuZ+STTZcuts << std::endl;
 std::cout << MMTT << " mmtt events fakeable" << std::endl;
 double MMTTt2 = eventTree->GetEntries(LMuZ+STTZcutsT2);
 double MMTTnt2 = eventTree->GetEntries(LMuZ+STTZcutsnT2);
 std::cout << "IFRM: " << IFRM << istd::endl;
 double mmtt = IFRM*IFRM*MMTT/(1-IFRM*IFRM);
 double mmttt2 = IFRM*1.5*IFRM*MMTTt2/(1-IFRM*1.5*IFRM)+IFRM*IFRM*MMTTnt2/(1-IFRM*IFRM);
 double mmttErr = sqrt(MMTT*IFRM*IFRM*IFRM*IFRM+4*IFRMErr*IFRMErr*MMTT*MMTT*IFRM*IFRM);
// cout << "Events In Control Region " << MMTT << endl;
 cout << "Background Est. for MMTT = " << mmtt << " +- " << mmttErr << endl;
 cout << "Background Est. for MMTT with t2 scaled = " << mmttt2 << " +- " << mmttErr << "(" << MMTTt2+MMTTnt2 << ") fakeable" << endl;
 e->cd();
 eleEleTauTauEventTreeID->cd();
 double EETT = eventTree->GetEntries(LEleZ+STTZcuts);
 double eett = IFRM*IFRM*EETT/(1-IFRM*IFRM);
 double eettErr = sqrt(EETT*IFRM*IFRM*IFRM*IFRM+4*IFRMErr*IFRMErr*EETT*EETT*IFRM*IFRM);
// cout << "Events In Control Region " << EETT << endl;
cout << "Background Est. for EETT = " << eett << " +- " << eettErr << endl;
e->cd();
eleEleEleTauEventTreeID->cd();
double EEET = eventTree->GetEntries(LEleZ+SETZcuts);
double eeet = IFRL*EEET/(1-IFRL);
double eeetErr = sqrt(IFRL*IFRL*EEET+EEET*EEET*IFRLErr*IFRLErr);
//cout << "Events In Control Region " << EEET << endl;
cout << "Background Est. for EEET = " << eeet << " +- " << eeetErr << endl;
m->cd();
muMuEleTauEventTreeID->cd();
double MMET = eventTree->GetEntries(LMuZ+SETZcuts);
double mmet = IFRL*MMET/(1-IFRL);
double mmetErr = sqrt(IFRL*IFRL*MMET+MMET*MMET*IFRLErr*IFRLErr);
//cout << "Events In Control Region " << MMET << endl;
cout << "Background Est. for MMET = " << mmet << " +- " << mmetErr << endl;
 m->cd();
 muMuMuTauEventTreeID->cd();
 double MMMT = eventTree->GetEntries(LMuZ+SMTZcuts);
 double mmmt = IFRL*MMMT/(1-IFRL);
 double mmmtErr = sqrt(IFRL*IFRL*MMMT+MMMT*MMMT*IFRLErr*IFRLErr);
// cout << "Events In Control Region " << MMMT << endl;
 cout << "Background Est. for MMMT = " << mmmt << " +- " << mmmtErr << endl;
 e->cd();
 eleEleMuTauEventTreeID->cd();
 double EEMT = eventTree->GetEntries(LEleZ+SMTZcuts);
 double eemt = IFRL*EEMT/(1-IFRL);
 double eemtErr = sqrt(IFRL*IFRL*EEMT+EEMT*EEMT*IFRLErr*IFRLErr);
// cout << "Events In Control Region " << EEMT << endl;
 cout << "Background Est. for EEMT = " << eemt << " +- " << eemtErr << endl;



//////////////Fitting, pt dependant fake rates///////////////////
tt->BayesDivide(n1,d1);
tt->GetXaxis()->SetTitle("#tau p_{T} GeV");
tt->GetYaxis()->SetTitle("Fake Rate");
tt->Draw("AP");
TF1 *myfit1 = new TF1("myfit1","[0] + [1]*exp([2]*x)", 15, 100);
myfit1->SetParameter(0, 0);
myfit1->SetParameter(1, 0);
myfit1->SetParameter(2, 0);
tt->Fit("myfit1","WR");
//l1=new TLine(15,IFRM,100,IFRM);
//l1->SetLineColor(38);
//l1->Draw();
C->SaveAs("FitPlots/tautau.pdf");
C->SaveAs("FitPlots/tautau.png");
C->SaveAs("FitPlots/tautau.C");
double c0 = myfit1->GetParameter(0);
double c1 = myfit1->GetParameter(1);
double c2 = myfit1->GetParameter(2);
double e0 = myfit1->GetParError(0);
double e1 = myfit1->GetParError(1);
double e2 = myfit1->GetParError(2);
lt->BayesDivide(n1VL,d1VL);
lt->GetXaxis()->SetTitle("#tau p_{T} GeV");
lt->GetYaxis()->SetTitle("Fake Rate");
lt->GetYaxis()->SetRangeUser(0,0.15);
lt->Draw("AP");
TF1 *myfit2 = new TF1("myfit2","[0] + [1]*exp([2]*x)", 15, 100);
myfit2->SetParameter(0, 0);
myfit2->SetParameter(1, 0);
myfit2->SetParameter(2, 0);
lt->Fit("myfit2","WR");
//l2=new TLine(15,IFRL,100,IFRL);
//l2->SetLineColor(38);
//l2->Draw();
C->SaveAs("FitPlots/tautauL.pdf");
C->SaveAs("FitPlots/tautauL.png");
C->SaveAs("FitPlots/tautauL.C");
double c0VL = myfit2->GetParameter(0);
double c1VL = myfit2->GetParameter(1);
double c2VL = myfit2->GetParameter(2);
double e0VL = myfit2->GetParError(0);
double e1VL = myfit2->GetParError(1);
double e2VL = myfit2->GetParError(2);
std::ostringstream S0;
std::ostringstream S1;
std::ostringstream S2;
std::ostringstream E0;
std::ostringstream E1;
std::ostringstream E2;
std::ostringstream S0VL;
std::ostringstream S1VL;
std::ostringstream S2VL;
std::ostringstream E0VL;
std::ostringstream E1VL;
std::ostringstream E2VL;
S0 << c0;
S1 << c1;
S2 << c2;
E0 << e0;
E1 << e1;
E2 << e2;
S0VL << c0VL;
S1VL << c1VL;
S2VL << c2VL;
E0VL << e0VL;
E1VL << e1VL;
E2VL << e2VL;
TString s0 = S0.str();
TString s1 = S1.str();
TString s2 = S2.str();
TString se0 = E0.str();
TString se1 = E1.str();
TString se2 = E2.str();
TString s0VL = S0VL.str();
TString s1VL = S1VL.str();
TString s2VL = S2VL.str();
TString se0VL = E0VL.str();
TString se1VL = E1VL.str();
TString se2VL = E2VL.str();
TString tt1 = "("+s0+"*z2l1Pt/z2l1Pt+"+s1+"*exp(z2l1Pt*"+s2+"))";
TString tt2 = "("+s0+"*z2l2Pt/z2l2Pt+"+s1+"*exp(z2l2Pt*"+s2+"))";
TString tte1 = "("+se0+"^2*z2l1Pt/z2l1Pt+("+se1+"^2+"+s1+"^2*z2l1Pt^2*"+se2+"^2)*exp(2*z2l1Pt*"+s2+"))";
TString tte2 = "("+se0+"^2*z2l2Pt/z2l2Pt+("+se1+"^2+"+s1+"^2*z2l2Pt^2*"+se2+"^2)*exp(2*z2l2Pt*"+s2+"))";
TString et = "("+s0VL+"*z2l2Pt/z2l2Pt+"+s1VL+"*exp(z2l2Pt*"+s2VL+"))";
TString mt = "("+s0VL+"*z2l2Pt/z2l2Pt+"+s1VL+"*exp(z2l2Pt*"+s2VL+"))";
TString ete = "("+se0VL+"^2*z2l2Pt/z2l2Pt+("+se1VL+"^2+"+s1VL+"^2*z2l2Pt^2*"+se2VL+"^2)*exp(2*z2l2Pt*"+s2VL+"))";
TString mte = "("+se0VL+"^2*z2l2Pt/z2l2Pt+("+se1VL+"^2+"+s1VL+"^2*z2l2Pt^2*"+se2VL+"^2)*exp(2*z2l2Pt*"+s2VL+"))";

/////////////////Apply fit to individual channels////////////////////////////////////
cout << "\\begin{table}[htbp]" << endl;
cout << "\\centering" << endl;
cout << "\\begin{tabular}{|c||c|c|c|c|c|}" << endl;
cout << "\\hline" << endl;
cout << " & $N_{ZZ}^{est}$ & Reducible background  & Observed \\\\" << endl;
cout << "\\hline" << endl;
cout << "\\hline" << endl;
m->cd();
muMuTauTauEventTreeID->cd();
eventTree->Draw("1>>ll(1,1,2)","("+LMuZ+STTZcuts+")*"+tt1+"*"+tt2+"/(1-"+tt1+"*"+tt2+")");
double llv = ll->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LMuZ+STTZcuts+")*"+tt1+"^2*"+tt2+"^2");
double llev1 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LMuZ+STTZcuts+")*"+tte1+"*"+tt2+"");
double llev2 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LMuZ+STTZcuts+")*"+tt1+"*"+tte2+"");
double llev3 = lle->GetBinContent(1);
double llev = sqrt(llev1+llev2*llev2+llev3*llev3);
printf("$\\mu\\mu\\tauh\\tauh$ & $--$ & $ %0.2f \\pm %0.2f (stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",llv,llev);
//cout << "MMTT fakeable: " << eventTree->GetEntries(LMuZ+STTZcuts) << endl;
//cout << "Background for MMTT = " << llv << " +- " << llev << endl;
//cout << "MMTT cuts: " << LMuZ << STTZcuts << endl;
//cout << "MMTT: " << llv/0.409 << endl;
e->cd();
eleEleTauTauEventTreeID->cd();
eventTree->Draw("1>>ll(1,1,2)","("+LEleZ+STTZcuts+")*"+tt1+"*"+tt2+"/(1-"+tt1+"*"+tt2+")");
double llv = ll->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LEleZ+STTZcuts+")*"+tt1+"^2*"+tt2+"^2");
double llev1 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LEleZ+STTZcuts+")*"+tte1+"*"+tt2+"");
double llev2 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LEleZ+STTZcuts+")*"+tt1+"*"+tte2+"");
double llev3 = lle->GetBinContent(1);
double llev = sqrt(llev1+llev2*llev2+llev3*llev3);/////
printf("$ee\\tauh\\tauh$ & $--$ & $ %0.2f \\pm  %0.2f (stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",llv,llev);
//cout << "EETT fakeable: " << eventTree->GetEntries(LEleZ+STTZcuts) << endl;
//cout << "Background for EETT = " << llv << " +- " << llev << endl;
//cout << "EETT cuts: " << LEleZ << STTZcuts << endl;
//cout << "EETT: " << llv/0.360 << endl;
e->cd();
eleEleEleTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LEleZ+SETZcuts+")*"+et+"/(1-"+et+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SETZcuts+")*"+et+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SETZcuts+")*"+ete+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
printf("$ee\\tau_{e}\\tauh$ & $--$ & $ %0.2f \\pm %0.2f (stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",lv,ler);
//cout << "EEET fakeable: " << eventTree->GetEntries(LEleZ+SETZcuts) << endl;
//cout << "Background for EEET = " << lv << " +- " << ler << endl;
//cout << "EEET cuts: " << LEleZ << SETZcuts << endl;
//cout << "EEET: " << lv/0.476 << endl;
m->cd();
muMuEleTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LMuZ+SETZcuts+")*"+et+"/(1-"+et+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SETZcuts+")*"+et+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SETZcuts+")*"+ete+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
printf("$\\mu\\mu\\tau_{e}\\tauh$ & $--$ & $ %0.2f \\pm %0.2f (stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",lv,ler);
//cout << "MMET fakeable: " << eventTree->GetEntries(LMuZ+SETZcuts) << endl;
//cout << "Background for MMET = " << lv << " +- " << ler << endl;
//cout << "MMET cuts: " << LMuZ << SETZcuts << endl;
//cout << "MMET: " << lv/0.345 << endl;
m->cd();
muMuMuTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LMuZ+SMTZcuts+")*"+mt+"/(1-"+mt+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SMTZcuts+")*"+mt+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SMTZcuts+")*"+mte+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
printf("$\\mu\\mu\\tau_{\\mu}\\tauh$ & $--$ & $ %0.2f \\pm %0.2f (stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",lv,ler);
//cout << "MMMT fakeable: " << eventTree->GetEntries(LMuZ+SMTZcuts) << endl;
//cout << "Background for MMMT = " << lv << " +- " << ler << endl;
//cout << "MMMT cuts: " << LMuZ << SMTZcuts << endl;
//cout << "MMMT: " << lv/0.147 << endl;
e->cd();
eleEleMuTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LEleZ+SMTZcuts+")*"+mt+"/(1-"+mt+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SMTZcuts+")*"+mt+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SMTZcuts+")*"+mte+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
printf("$ee\\tau_{\\mu}\\tauh$ & $--$ & $ %0.2f \\pm %0.2f (stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",lv,ler);
//cout << "EEMT fakeable: " << eventTree->GetEntries(LEleZ+SMTZcuts) << endl;
//cout << "Background for EEMT = " << lv << " +- " << ler << endl;
//cout << "EEMT cuts: " << LEleZ << SMTZcuts << endl;
//cout << "EEMT: " << lv/0.245 << endl;


////////////////////////////// Integral Method for Leptons /////////////////////////////////////////////
double IFREle,IFREleErr,IFRMu,IFRMuErr;
IFREle = NE/DE;
IFREleErr = sqrt(NE/(DE*DE)+NE*NE/(DE*DE*DE));
IFRMu = NM/DM;
IFRMuErr = sqrt(NM/(DM*DM)+NM*NM/(DM*DM*DM));
//cout << "Integral ele fakerate = " << IFREle << " +- " << IFREleErr << endl;
//cout << "Integral mu fakerate = " << IFRMu << " +- " << IFRMuErr << endl;
e->cd();
eleEleEleEleEventTreeID->cd();
double EEEE = eventTree->GetEntries(LEleZ+SEEZcuts);
double eeee = IFREle*IFREle*EEEE/(1-IFREle*IFREle);
double eeeeErr = sqrt(EEEE*IFREle*IFREle*IFREle*IFREle+4*IFREleErr*IFREleErr*EEEE*EEEE*IFREle*IFREle);
//cout << "EEEE cuts: " << LEleZ+SEEZcuts << endl;
//cout << "Background Est. for EEEE = " << eeee << " +- " << eeeeErr << endl;
//cout << "EEEE fakeable: " << EEEE << endl;
e->cd();
eleEleEleMuEventTreeID->cd();
double EEEM = eventTree->GetEntries(LEleZ+SEMZcuts);
double eeem = IFREle*IFRMu*EEEM/(1-IFREle*IFRMu);
double eeemErr = sqrt(EEEM*IFREle*IFREle*IFRMu*IFRMu+(IFREleErr*IFREleErr*IFRMu*IFRMu+IFRMuErr*IFRMuErr*IFREle*IFREle)*EEEM*EEEM);
printf("$ee\\tau_{e}\\tau_{\\mu}$ & $--$ & $ %0.2f \\pm %0.2f(stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",eeem,eeemErr);
//cout << "Background for EEEM = " << eeem << " +- " << eeemErr << endl;
//cout << "EEEM cuts: " << LEleZ << SEMZcuts << endl;
//cout << "EEEM: " << eeem/0.0841 << endl;
//cout << "EEEM fakeable: " << EEEM << endl;
m->cd();
muMuEleMuEventTreeID->cd();
double MMEM = eventTree->GetEntries(LMuZ+SEMZcuts);
double mmem = IFREle*IFRMu*MMEM/(1-IFREle*IFRMu);
double mmemErr = sqrt(MMEM*IFREle*IFREle*IFRMu*IFRMu+(IFREleErr*IFREleErr*IFRMu*IFRMu+IFRMuErr*IFRMuErr*IFREle*IFREle)*MMEM*MMEM);
printf("$\\mu\\mu\\tau_{e}\\tau_{\\mu}$ & $--$ & $ %0.2f \\pm %0.2f (stat.) \\pm XX (sys.)$ & $ -- $\\\\ \n",mmem,mmemErr);
cout << "\\hline" << endl;
cout << "\\end{tabular}" << endl;
cout << "\\end{table}" << endl;
//cout << "Background for MMEM = " << mmem << " +- " << mmemErr << endl;
//cout << "MMEM cuts: " << LMuZ << SEMZcuts << endl;
//cout << "MMEM: " << mmem/0.1367 << endl;
//cout << "MMEM fakeable: " << MMEM << endl;
m->cd();
muMuEleEleEventTreeID->cd();
double MMEE = eventTree->GetEntries(LMuZ+SEEZcuts);
double mmee = IFREle*IFREle*MMEE/(1-IFREle*IFREle);
double mmeeErr = sqrt(MMEE*IFREle*IFREle*IFREle*IFREle+4*IFREleErr*IFREleErr*MMEE*MMEE*IFREle*IFREle);
//	cout << "MMEE cuts: " << LMuZ+SEEZcuts << endl;
//cout << "MMEE cuts: " << LMuZ+SEEZcuts << endl;
//cout << "Background Est. for MMEE = " << mmee << " +- " << mmeeErr << endl;
//cout << "Events In Control Region " << MMEE << endl;
e->cd();
eleEleMuMuEventTreeID->cd();
double EEMM = eventTree->GetEntries(LEleZ+SMMZcuts);
double eemm = IFRMu*IFRMu*EEMM/(1-IFRMu*IFRMu);
double eemmErr = sqrt(EEMM*IFRMu*IFRMu*IFRMu*IFRMu+4*IFRMuErr*IFRMuErr*IFRMu*IFRMu*EEMM*EEMM);
//cout << "Background Est. for EEMM = " << eemm << " +- " << eemmErr << endl;
//cout << "Events In Control Region " << EEMM << endl;
m->cd();
muMuMuMuEventTreeID->cd();
double MMMM = eventTree->GetEntries(LMuZ+SMMZcuts);
double mmmm = IFRMu*IFRMu*MMMM/(1-IFRMu*IFRMu);
double mmmmErr = sqrt(MMMM*IFRMu*IFRMu*IFRMu*IFRMu+4*IFRMuErr*IFRMuErr*IFRMu*IFRMu*MMMM*MMMM);
//cout << "MMMM cuts: " << LMuZ+SMMZcuts << endl;
//cout << "Background Est. for MMMM = " << mmmm << " +- " << mmmmErr << endl;
//cout << "Events In Control Region " << MMMM << endl;

mm->BayesDivide(nm,dm);
mm->GetXaxis()->SetTitle("#mu p_{T}");
mm->GetYaxis()->SetRangeUser(0,0.6);
mm->GetYaxis()->SetTitle("Fake rate");
mm->Draw("AP");
C->SaveAs("FitPlots/mu.png");
ee->BayesDivide(ne,de);
ee->GetXaxis()->SetTitle("e p_{T}");
ee->GetYaxis()->SetTitle("Fake rate");
ee->GetYaxis()->SetRangeUser(0,0.6);
ee->Draw("AP");
C->SaveAs("FitPlots/ele.png");


}
