{

TFile *e = new TFile("sandbox/zzeedata-Aug5/DATA.root");
TFile *m = new TFile("sandbox/zzmm-latest/DATA.root");
TString LEleZ = "HLT_Any&&z1Mass>60&&z1Mass<120&&z1l1CiCTight&1==1&&z1l2CiCTight&1==1&&z1l1MissHits<2&&z1l2MissHits<2&&z1l1RelPfIsoRho<0.2&&z1l2RelPfIsoRho<0.2&&z1l1Pt>20&&z1l2Pt>10";
TString LMuZ = "HLT_Any&&z1Mass>60&&z1Mass<120&&z1l1RelPfIsoRho<0.25&&z1l2RelPfIsoRho<0.25&&z1l1Pt>20&&z1l2Pt>10";

TString STTZt1n = "&&z2l1Pt>15&&z2l2Pt>15&&z2l1EleVeto&&z2l2EleVeto&&z2l1MediumIso&&z2l1MuVeto&&z2l2MuVeto&&z2Mass>30&&z2Mass<80&&z2Charge!=0";
TString STTZt2n = "&&z2l1Pt>15&&z2l2Pt>15&&z2l1EleVeto&&z2l2EleVeto&&z2l2MediumIso&&z2l1MuVeto&&z2l2MuVeto&&z2Mass>30&&z2Mass<80&&z2Charge!=0";
TString STTZt1nVL = "&&z2l1Pt>15&&z2l2Pt>15&&z2l1EleVeto&&z2l2EleVeto&&z2l1LooseIso&&z2l1MuVeto&&z2l2MuVeto&&z2Mass>30&&z2Mass<80&&z2Charge!=0";
TString STTZt2nVL = "&&z2l1Pt>15&&z2l2Pt>15&&z2l1EleVeto&&z2l2EleVeto&&z2l2LooseIso&&z2l1MuVeto&&z2l2MuVeto&&z2Mass>30&&z2Mass<80&&z2Charge!=0";
TString STTZtd  = "&&z2l1Pt>15&&z2l2Pt>15&&z2l1EleVeto&&z2l2EleVeto&&z2l1MuVeto&&z2l2MuVeto&&z2Mass>30&&z2Mass<80&&z2Charge!=0";

TString SEEZ2n = "&&z2l1Pt>7&&z2l2Pt>7&&z2Charge!=0&&z2l1CiCTight&1==1&&z2l2CiCTight&1==1&&z2l1MissHits<2&&z2l2MissHits<2&&z2l2RelPfIsoRho<0.2&&(z2l1Pt+z2l2Pt)>20&&met<20";
TString SEEZ1n = "&&z2l1Pt>7&&z2l2Pt>7&&z2Charge!=0&&z2l1CiCTight&1==1&&z2l2CiCTight&1==1&&z2l1MissHits<2&&z2l2MissHits<2&&z2l1RelPfIsoRho<0.2&&(z2l1Pt+z2l2Pt)>20&&met<20";
TString SMMZ2n = "&&z2l1Pt>5&&z2l2Pt>5&&z2Charge!=0&&z2l2RelPfIsoRho<0.25&&(z2l1Pt+z2l2Pt)>20&&met<20";
TString SMMZ1n = "&&z2l1Pt>5&&z2l2Pt>5&&z2Charge!=0&&z2l1RelPfIsoRho<0.25&&(z2l1Pt+z2l2Pt)>20&&met<20";
TString SEMZMn = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1CiCTight&1==1&&z2l1MissHits<2&&z2l2RelPfIsoRho<0.25&&z2Charge!=0&&met<20";
TString SEMZEn = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1CiCTight&1==1&&z2l1MissHits<2&&z2l1RelPfIsoRho<0.2&&z2Charge!=0&&met<20";
TString SEEZtd  = "&&z2l1Pt>7&&z2l2Pt>7&&z2Charge!=0&&z2l1CiCTight&1==1&&z2l2CiCTight&1==1&&z2l1MissHits<2&&z2l2MissHits<2&&(z2l1Pt+z2l2Pt)>20&&met<20";
TString SMMZtd  = "&&z2l1Pt>5&&z2l2Pt>5&&z2Charge!=0&&(z2l1Pt+z2l2Pt)>20&&met<20";
TString SEMZtd  = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1CiCTight&1==1&&z2l1MissHits<2&&z2Charge!=0&&met<20";
TString SMTZn = "&&z2l2EleVeto&&z2l2MuVetoTight&&z2l1RelPfIsoRho<0.25&&z2l2Pt>20&&z2l1Pt>10&&z2Charge!=0&&z2Mass>30&&z2Mass<80&&met<20";
TString SETZn = "&&z2l2EleVeto&&z2l1CiCTight&1==1&&z2l2Pt>20&&z2l1Pt>10&&z2l1RelPfIsoRho<0.2&&z2l1MissHits<2&&z2l2MuVeto&&z2Charge!=0&&z2Mass>30&&z2Mass<80&&met<20";
TString SMTZnT = "&&z2l2EleVeto&&z2l2MuVetoTight&&z2l1RelPfIsoRho<0.15&&z2l2Pt>20&&z2l1Pt>10&&z2Charge!=0&&z2Mass>30&&z2Mass<80&&met<20";
TString SETZnT = "&&z2l2EleVeto&&z2l1CiCTight&1==1&&z2l2Pt>20&&z2l1Pt>10&&z2l1RelPfIsoRho<0.05&&z2l1MissHits==0&&z2l2MuVeto&&z2Charge!=0&&z2Mass>30&&z2Mass<80&&met<20";
TString SMTZd = "&&z2l2EleVeto&&z2l2MuVetoTight&&z2l2Pt>20&&z2l1Pt>10&&z2Charge!=0&&z2Mass>30&&z2Mass<80&&met<20";
TString SETZd = "&&z2l2EleVeto&&z2l1CiCTight&1==1&&z2l2Pt>20&&z2l1Pt>10&&z2l1MissHits<2&&z2l2MuVeto&&z2Charge!=0&&z2Mass>30&&z2Mass<80&&met<20";

TString SEEZcuts = "&&z2l1Pt>7&&z2l2Pt>7&&z2Charge==0&&z2l1CiCTight&1==1&&z2l2CiCTight&1==1&&z2l1MissHits<2&&z2l2MissHits<2&&z2l1RelPfIsoRho>0.2&&z2l2RelPfIsoRho>0.2&&(z2l1Pt+z2l2Pt)>20";
TString SMMZcuts = "&&z2l1Pt>5&&z2l2Pt>5&&z2Charge==0&&z2l2RelPfIsoRho>0.25&&z2l1RelPfIsoRho>0.25&&(z2l1Pt+z2l2Pt)>20";
TString SEMZcuts = "&&z2l1Pt>10&&z2l2Pt>10&&z2l1CiCTight&1==1&&z2l1MissHits<2&&z2Charge==0&&z2l1RelPfIsoRho>0.2&&z2l2RelPfIsoRho>0.25";
TString STTZcuts = "&&z2l1Pt>20&&z2l2Pt>20&&z2l1EleVeto&&z2l2EleVeto&&!z2l1MediumIso&&!z2l2MediumIso&&z2l1MuVeto&&z2l2MuVeto&&z2Mass>30&&z2Mass<80&&z2Charge==0";
TString SMTZcuts = "&&z2l2EleVeto&&!z2l2LooseIso&&z2l2MuVetoTight&&z2l1RelPfIsoRho<0.15&&z2l2Pt>20&&z2l1Pt>10&&z2Charge==0&&z2Mass>30&&z2Mass<80";
TString SETZcuts = "&&z2l2EleVeto&&z2l1CiCTight&1==1&&!z2l2LooseIso&&z2l2Pt>20&&z2l1Pt>10&&z2l1RelPfIsoRho<0.05&&z2l1MissHits==0&&z2l2MuVeto&&z2Charge==0&&z2Mass>30&&z2Mass<80";
gROOT->ProcessLine(".!mkdir FitPlots");

////////////////////////////////Measure Fake Rate for Leptons////////////////////////////////////////////

e->cd();
eleEleEleMuEventTreeID->cd();
TGraphAsymmErrors *ee = new TGraphAsymmErrors();
TGraphAsymmErrors *mm = new TGraphAsymmErrors();
double DE,NE,DM,NM,NET,NMT,DET,DMT;
TCanvas *C = new TCanvas();
TH1F *nm = new TH1F("nm", "nm", 10, 0,100);
TH1F *dm = new TH1F("dm", "dm", 10, 0,100);
TH1F *ne = new TH1F("ne", "ne", 10, 0,100);
TH1F *de = new TH1F("de", "de", 10, 0,100);
eventTree->Draw("z2l1Pt>>ne",LEleZ+SEMZEn);
eventTree->Draw("z2l2Pt>>nm",LEleZ+SEMZMn);
eventTree->Draw("z2l1Pt>>de",LEleZ+SEMZtd);
eventTree->Draw("z2l2Pt>>dm",LEleZ+SEMZtd);
NE = eventTree->GetEntries(LEleZ+SEMZEn);
DE = eventTree->GetEntries(LEleZ+SEMZtd);
NM = eventTree->GetEntries(LEleZ+SEMZMn);
DM = eventTree->GetEntries(LEleZ+SEMZtd);
m->cd();
muMuEleMuEventTreeID->cd();
eventTree->Draw("z2l1Pt>>ne1(10,0,100)",LMuZ+SEMZEn);
eventTree->Draw("z2l2Pt>>nm1(10,0,100)",LMuZ+SEMZMn);
eventTree->Draw("z2l1Pt>>de1(10,0,100)",LMuZ+SEMZtd);
eventTree->Draw("z2l2Pt>>dm1(10,0,100)",LMuZ+SEMZtd);
ne->Add(ne,ne1);
nm->Add(nm,nm1);
de->Add(de,de1);
dm->Add(dm,dm1);
NE += eventTree->GetEntries(LMuZ+SEMZEn);
DE += eventTree->GetEntries(LMuZ+SEMZtd);
NM += eventTree->GetEntries(LMuZ+SEMZMn);
DM += eventTree->GetEntries(LMuZ+SEMZtd);
m->cd();
muMuMuMuEventTreeID->cd();
eventTree->Draw("z2l1Pt>>nm1(10,0,100)",LMuZ+SMMZ1n);
eventTree->Draw("z2l2Pt>>nm2(10,0,100)",LMuZ+SMMZ2n);
eventTree->Draw("z2l1Pt>>dm1(10,0,100)",LMuZ+SMMZtd);
eventTree->Draw("z2l2Pt>>dm2(10,0,100)",LMuZ+SMMZtd);
nm->Add(nm,nm1);
nm->Add(nm,nm2);
dm->Add(dm,dm1);
dm->Add(dm,dm2);
NM += eventTree->GetEntries(LMuZ+SMMZ1n);
NM += eventTree->GetEntries(LMuZ+SMMZ2n);
DM += 2*eventTree->GetEntries(LMuZ+SMMZtd);
e->cd();
eleEleMuMuEventTreeID->cd();
eventTree->Draw("z2l1Pt>>nm1(10,0,100)",LEleZ+SMMZ1n);
eventTree->Draw("z2l2Pt>>nm2(10,0,100)",LEleZ+SMMZ2n);
eventTree->Draw("z2l1Pt>>dm1(10,0,100)",LEleZ+SMMZtd);
eventTree->Draw("z2l2Pt>>dm2(10,0,100)",LEleZ+SMMZtd);
nm->Add(nm,nm1);
nm->Add(nm,nm2);
dm->Add(dm,dm1);
dm->Add(dm,dm2);
NM += eventTree->GetEntries(LEleZ+SMMZ1n);
NM += eventTree->GetEntries(LEleZ+SMMZ2n);
DM += 2*eventTree->GetEntries(LEleZ+SMMZtd);
m->cd();
muMuEleEleEventTreeID->cd();
eventTree->Draw("z2l1Pt>>ne1(10,0,100)",LMuZ+SEEZ1n);
eventTree->Draw("z2l2Pt>>ne2(10,0,100)",LMuZ+SEEZ2n);
eventTree->Draw("z2l1Pt>>de1(10,0,100)",LMuZ+SEEZtd);
eventTree->Draw("z2l2Pt>>de2(10,0,100)",LMuZ+SEEZtd);
ne->Add(ne,ne1);
ne->Add(ne,ne2);
de->Add(de,de1);
de->Add(de,de2);
NE += eventTree->GetEntries(LMuZ+SEEZ1n);
NE += eventTree->GetEntries(LMuZ+SEEZ2n);
DE += 2*eventTree->GetEntries(LMuZ+SEEZtd);
e->cd();
eleEleEleEleEventTreeID->cd();
eventTree->Draw("z2l1Pt>>ne1(10,0,100)",LEleZ+SEEZ1n);
eventTree->Draw("z2l2Pt>>ne2(10,0,100)",LEleZ+SEEZ2n);
eventTree->Draw("z2l1Pt>>de1(10,0,100)",LEleZ+SEEZtd);
eventTree->Draw("z2l2Pt>>de2(10,0,100)",LEleZ+SEEZtd);
ne->Add(ne,ne1);
ne->Add(ne,ne2);
de->Add(de,de1);
de->Add(de,de2);
NE += eventTree->GetEntries(LEleZ+SEEZ1n);
NE += eventTree->GetEntries(LEleZ+SEEZ2n);
DE += 2*eventTree->GetEntries(LEleZ+SEEZtd);
e->cd();
eleEleEleTauEventTreeID->cd();
eventTree->Draw("z2l1Pt>>ne1(10,0,100)",LEleZ+SETZn);
eventTree->Draw("z2l1Pt>>de1(10,0,100)",LEleZ+SETZd);
ne->Add(ne,ne1);
de->Add(de,de1);
NE += eventTree->GetEntries(LEleZ+SETZn);
NET = eventTree->GetEntries(LEleZ+SETZnT);
DET = eventTree->GetEntries(LEleZ+SETZd);
DE += eventTree->GetEntries(LEleZ+SETZd);
m->cd();
muMuEleTauEventTreeID->cd();
eventTree->Draw("z2l1Pt>>ne1(10,0,100)",LMuZ+SETZn);
eventTree->Draw("z2l1Pt>>de1(10,0,100)",LMuZ+SETZd);
ne->Add(ne,ne1);
de->Add(de,de1);
NE += eventTree->GetEntries(LMuZ+SETZn);
NET += eventTree->GetEntries(LMuZ+SETZnT);
DET += eventTree->GetEntries(LMuZ+SETZd);
DE += eventTree->GetEntries(LMuZ+SETZd);
m->cd();
muMuMuTauEventTreeID->cd();
eventTree->Draw("z2l1Pt>>nm1(10,0,100)",LMuZ+SMTZn);
eventTree->Draw("z2l1Pt>>dm1(10,0,100)",LMuZ+SMTZd);
nm->Add(nm,nm1);
dm->Add(dm,dm1);
NM += eventTree->GetEntries(LMuZ+SMTZn);
NMT = eventTree->GetEntries(LMuZ+SMTZnT);
DMT += eventTree->GetEntries(LMuZ+SMTZd);
DM += eventTree->GetEntries(LMuZ+SMTZd);
e->cd();
eleEleMuTauEventTreeID->cd();
eventTree->Draw("z2l1Pt>>nm1(10,0,100)",LEleZ+SMTZn);
eventTree->Draw("z2l1Pt>>dm1(10,0,100)",LEleZ+SMTZd);
nm->Add(nm,nm1);
dm->Add(dm,dm1);
NM += eventTree->GetEntries(LEleZ+SMTZn);
DMT += eventTree->GetEntries(LEleZ+SMTZd);
DM += eventTree->GetEntries(LEleZ+SMTZd);


////////////////////////////////////// Measure fake rate for Taus  ////////////////////////////////////////////////////
//Two channels combined for increased statistics: EETT, MMTT

double DTau,NLoose,NMed;
e->cd();
eleEleTauTauEventTreeID->cd();
TGraphAsymmErrors *tt = new TGraphAsymmErrors();
TGraphAsymmErrors *lt = new TGraphAsymmErrors();
TH1F *n1 = new TH1F("n1", "n1", 10, 0,100);
TH1F *d1 = new TH1F("d1", "d1", 10, 0,100);
TH1F *n1VL = new TH1F("n1VL", "n1VL", 10, 0,100);
TH1F *d1VL = new TH1F("d1VL", "d1VL", 10, 0,100);
eventTree->Draw("z2l1Pt>>n1",LEleZ+STTZt1n);
eventTree->Draw("z2l2Pt>>n2(10,0,100)",LEleZ+STTZt2n);
eventTree->Draw("z2l1Pt>>n1VL",LEleZ+STTZt1nVL);
eventTree->Draw("z2l2Pt>>n2VL(10,0,100)",LEleZ+STTZt2nVL);
n1->Add(n1,n2);
n1VL->Add(n1VL,n2VL);
NLoose = eventTree->GetEntries(LEleZ+STTZt1nVL+"&&z2l1Pt>20&&z2l2Pt>20");
NLoose += eventTree->GetEntries(LEleZ+STTZt2nVL+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1LooseIso");
NMed = eventTree->GetEntries(LEleZ+STTZt1n+"&&z2l1Pt>20&&z2l2Pt>20");
NMed += eventTree->GetEntries(LEleZ+STTZt2n+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1MediumIso");
eventTree->Draw("z2l1Pt>>d1",LEleZ+STTZtd);
eventTree->Draw("z2l2Pt>>d2(10,0,100)",LEleZ+STTZtd);
eventTree->Draw("z2l1Pt>>d1VL",LEleZ+STTZtd);
eventTree->Draw("z2l2Pt>>d2VL(10,0,100)",LEleZ+STTZtd);
d1->Add(d1,d2);
d1VL->Add(d1VL,d2VL);
DTau = 2*eventTree->GetEntries(LEleZ+STTZtd+"&&z2l1Pt>20&&z2l2Pt>20");
m->cd();
muMuTauTauEventTreeID->cd();
eventTree->Draw("z2l1Pt>>n3(10,0,100)",LMuZ+STTZt1n);
eventTree->Draw("z2l1Pt>>n3VL(10,0,100)",LMuZ+STTZt1nVL);
n1->Add(n1,n3);
n1VL->Add(n1VL,n3VL);
eventTree->Draw("z2l2Pt>>n4(10,0,100)",LMuZ+STTZt2n);
eventTree->Draw("z2l2Pt>>n4VL(10,0,100)",LMuZ+STTZt2nVL);
n1->Add(n1,n4);
n1VL->Add(n1VL,n4VL);
eventTree->Draw("z2l1Pt>>d3(10,0,100)",LMuZ+STTZtd);
eventTree->Draw("z2l1Pt>>d3VL(10,0,100)",LMuZ+STTZtd);
d1->Add(d1,d3);
d1VL->Add(d1VL,d3VL);
eventTree->Draw("z2l2Pt>>d4(10,0,100)",LMuZ+STTZtd);
eventTree->Draw("z2l2Pt>>d4VL(10,0,100)",LMuZ+STTZtd);
d1->Add(d1,d4);
d1VL->Add(d1VL,d4VL);
NLoose += eventTree->GetEntries(LMuZ+STTZt1nVL+"&&z2l1Pt>20&&z2l2Pt>20");
NLoose += eventTree->GetEntries(LMuZ+STTZt2nVL+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1LooseIso");
NMed += eventTree->GetEntries(LMuZ+STTZt1n+"&&z2l1Pt>20&&z2l2Pt>20");
NMed += eventTree->GetEntries(LMuZ+STTZt2n+"&&z2l1Pt>20&&z2l2Pt>20&&!z2l1MediumIso");
DTau += 2*eventTree->GetEntries(LMuZ+STTZtd+"&&z2l1Pt>20&&z2l2Pt>20");


//////////////Integral Fake Rate >20/////////////////////

// double IFRL,IFRLErr,IFRM,IFRMErr,IFRET,IFRMT,IFRETErr,IFRMTErr;
// IFRET = NET/DET;
// IFRMT = NMT/DMT;
// IFRL = NLoose/DTau;
// IFRLErr = sqrt(NLoose/(DTau*DTau)+NLoose*NLoose/(DTau*DTau*DTau));
// IFRM = NMed/DTau;
// IFRMErr = sqrt(NMed/(DTau*DTau)+NMed*NMed/(DTau*DTau*DTau));
// cout << "Integral Loose Fakerate = " << IFRL << " +- " << IFRLErr << endl;
// cout << "Integral Medium Fakerate = " << IFRM << " +- " << IFRMErr << endl;
// cout << "Integral Loose Fakerate = " << IFRET << " +- " << IFRETErr << endl;
// cout << "Integral Medium Fakerate = " << IFRMT << " +- " << IFRMTErr << endl;
// 
// m->cd();
// muMuTauTauEventTreeID->cd();
// double MMTT = eventTree->GetEntries(LMuZ+STTZcuts);
// double mmtt = IFRM*IFRM*MMTT/(1-IFRM*IFRM);
// double mmttErr = sqrt(MMTT*IFRM*IFRM*IFRM*IFRM+4*IFRMErr*IFRMErr*MMTT*MMTT*IFRM*IFRM);
// cout << "Events In Control Region " << MMTT << endl;
// cout << "Background Est. for MMTT = " << mmtt << " +- " << mmttErr << endl;
// e->cd();
// eleEleTauTauEventTreeID->cd();
// double EETT = eventTree->GetEntries(LEleZ+STTZcuts);
// double eett = IFRM*IFRM*EETT/(1-IFRM*IFRM);
// double eettErr = sqrt(EETT*IFRM*IFRM*IFRM*IFRM+4*IFRMErr*IFRMErr*EETT*EETT*IFRM*IFRM);
// cout << "Events In Control Region " << EETT << endl;
// cout << "Background Est. for EETT = " << eett << " +- " << eettErr << endl;
// e->cd();
// eleEleEleTauEventTreeID->cd();
// double EEET = eventTree->GetEntries(LEleZ+SETZcuts);
// double eeet = IFRL*EEET/(1-IFRL);
// double eeetErr = sqrt(IFRL*IFRL*EEET+EEET*EEET*IFRLErr*IFRLErr);
// cout << "Events In Control Region " << EEET << endl;
// cout << "Background Est. for EEET = " << eeet << " +- " << eeetErr << endl;
// m->cd();
// muMuEleTauEventTreeID->cd();
// double MMET = eventTree->GetEntries(LMuZ+SETZcuts);
// double mmet = IFRL*MMET/(1-IFRL);
// double mmetErr = sqrt(IFRL*IFRL*MMET+MMET*MMET*IFRLErr*IFRLErr);
// cout << "Events In Control Region " << MMET << endl;
// cout << "Background Est. for MMET = " << mmet << " +- " << mmetErr << endl;
// m->cd();
// muMuMuTauEventTreeID->cd();
// double MMMT = eventTree->GetEntries(LMuZ+SMTZcuts);
// double mmmt = IFRL*MMMT/(1-IFRL);
// double mmmtErr = sqrt(IFRL*IFRL*MMMT+MMMT*MMMT*IFRLErr*IFRLErr);
// cout << "Events In Control Region " << MMMT << endl;
// cout << "Background Est. for MMMT = " << mmmt << " +- " << mmmtErr << endl;
// e->cd();
// eleEleMuTauEventTreeID->cd();
// double EEMT = eventTree->GetEntries(LEleZ+SMTZcuts);
// double eemt = IFRL*EEMT/(1-IFRL);
// double eemtErr = sqrt(IFRL*IFRL*EEMT+EEMT*EEMT*IFRLErr*IFRLErr);
// cout << "Events In Control Region " << EEMT << endl;
// cout << "Background Est. for EEMT = " << eemt << " +- " << eemtErr << endl;



//////////////Fitting, pt dependant fake rates///////////////////
tt->BayesDivide(n1,d1);
tt->GetXaxis()->SetTitle("#tau p_{T} GeV");
tt->GetYaxis()->SetTitle("Fake Rate");
tt->Draw("AP");
TF1 *myfit1 = new TF1("myfit1","[0] + [1]*exp([2]*x)", 15, 60);
myfit1->SetParameter(0, 0);
myfit1->SetParameter(1, 0);
myfit1->SetParameter(2, 0);
tt->Fit("myfit1","WR");
//l1=new TLine(15,IFRM,100,IFRM);
//l1->SetLineColor(38);
//l1->Draw();
C->SaveAs("FitPlots/tautau.png");
C->SaveAs("FitPlots/tautau.C");
double c0 = myfit1->GetParameter(0);
double c1 = myfit1->GetParameter(1);
double c2 = myfit1->GetParameter(2);
double e0 = myfit1->GetParError(0);
double e1 = myfit1->GetParError(1);
double e2 = myfit1->GetParError(2);
lt->BayesDivide(n1VL,d1VL);
lt->GetXaxis()->SetTitle("#tau p_{T} GeV");
lt->GetYaxis()->SetTitle("Fake Rate");
lt->Draw("AP");
TF1 *myfit2 = new TF1("myfit2","[0] + [1]*exp([2]*x)", 15, 60);
myfit2->SetParameter(0, 0);
myfit2->SetParameter(1, 0);
myfit2->SetParameter(2, 0);
lt->Fit("myfit2","WR");
//l2=new TLine(15,IFRL,100,IFRL);
//l2->SetLineColor(38);
//l2->Draw();
C->SaveAs("FitPlots/tautauL.png");
C->SaveAs("FitPlots/tautauL.C");
double c0VL = myfit2->GetParameter(0);
double c1VL = myfit2->GetParameter(1);
double c2VL = myfit2->GetParameter(2);
double e0VL = myfit2->GetParError(0);
double e1VL = myfit2->GetParError(1);
double e2VL = myfit2->GetParError(2);
std::ostringstream S0;
std::ostringstream S1;
std::ostringstream S2;
std::ostringstream E0;
std::ostringstream E1;
std::ostringstream E2;
std::ostringstream S0VL;
std::ostringstream S1VL;
std::ostringstream S2VL;
std::ostringstream E0VL;
std::ostringstream E1VL;
std::ostringstream E2VL;
S0 << c0;
S1 << c1;
S2 << c2;
E0 << e0;
E1 << e1;
E2 << e2;
S0VL << c0VL;
S1VL << c1VL;
S2VL << c2VL;
E0VL << e0VL;
E1VL << e1VL;
E2VL << e2VL;
TString s0 = S0.str();
TString s1 = S1.str();
TString s2 = S2.str();
TString se0 = E0.str();
TString se1 = E1.str();
TString se2 = E2.str();
TString s0VL = S0VL.str();
TString s1VL = S1VL.str();
TString s2VL = S2VL.str();
TString se0VL = E0VL.str();
TString se1VL = E1VL.str();
TString se2VL = E2VL.str();
TString tt1 = "("+s0+"*z2l1Pt/z2l1Pt+"+s1+"*exp(z2l1Pt*"+s2+"))";
TString tt2 = "("+s0+"*z2l2Pt/z2l2Pt+"+s1+"*exp(z2l2Pt*"+s2+"))";
TString tte1 = "("+se0+"^2*z2l1Pt/z2l1Pt+("+se1+"^2+"+s1+"^2*z2l1Pt^2*"+se2+"^2)*exp(2*z2l1Pt*"+s2+"))";
TString tte2 = "("+se0+"^2*z2l2Pt/z2l2Pt+("+se1+"^2+"+s1+"^2*z2l2Pt^2*"+se2+"^2)*exp(2*z2l2Pt*"+s2+"))";
TString et = "("+s0VL+"*z2l2Pt/z2l2Pt+"+s1VL+"*exp(z2l2Pt*"+s2VL+"))";
TString mt = "("+s0VL+"*z2l2Pt/z2l2Pt+"+s1VL+"*exp(z2l2Pt*"+s2VL+"))";
TString ete = "("+se0VL+"^2*z2l2Pt/z2l2Pt+("+se1VL+"^2+"+s1VL+"^2*z2l2Pt^2*"+se2VL+"^2)*exp(2*z2l2Pt*"+s2VL+"))";
TString mte = "("+se0VL+"^2*z2l2Pt/z2l2Pt+("+se1VL+"^2+"+s1VL+"^2*z2l2Pt^2*"+se2VL+"^2)*exp(2*z2l2Pt*"+s2VL+"))";

/////////////////Apply fit to individual channels////////////////////////////////////

m->cd();
muMuTauTauEventTreeID->cd();
eventTree->Draw("1>>ll(1,1,2)","("+LMuZ+STTZcuts+")*"+tt1+"*"+tt2+"/(1-"+tt1+"*"+tt2+")");
double llv = ll->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LMuZ+STTZcuts+")*"+tt1+"^2*"+tt2+"^2");
double llev1 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LMuZ+STTZcuts+")*"+tte1+"*"+tt2+"");
double llev2 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LMuZ+STTZcuts+")*"+tt1+"*"+tte2+"");
double llev3 = lle->GetBinContent(1);
double llev = sqrt(llev1+llev2*llev2+llev3*llev3);
cout << "Background for MMTT = " << llv << " +- " << llev << endl;
e->cd();
eleEleTauTauEventTreeID->cd();
eventTree->Draw("1>>ll(1,1,2)","("+LEleZ+STTZcuts+")*"+tt1+"*"+tt2+"/(1-"+tt1+"*"+tt2+")");
double llv = ll->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LEleZ+STTZcuts+")*"+tt1+"^2*"+tt2+"^2");
double llev1 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LEleZ+STTZcuts+")*"+tte1+"*"+tt2+"");
double llev2 = lle->GetBinContent(1);
eventTree->Draw("1>>lle(1,1,2)","("+LEleZ+STTZcuts+")*"+tt1+"*"+tte2+"");
double llev3 = lle->GetBinContent(1);
double llev = sqrt(llev1+llev2*llev2+llev3*llev3);
cout << "Background for EETT = " << llv << " +- " << llev << endl;
e->cd();
eleEleEleTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LEleZ+SETZcuts+")*"+et+"/(1-"+et+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SETZcuts+")*"+et+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SETZcuts+")*"+ete+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
cout << "Background for EEET = " << lv << " +- " << ler << endl;
m->cd();
muMuEleTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LMuZ+SETZcuts+")*"+et+"/(1-"+et+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SETZcuts+")*"+et+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SETZcuts+")*"+ete+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
cout << "Background for MMET = " << lv << " +- " << ler << endl;
m->cd();
muMuMuTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LMuZ+SMTZcuts+")*"+mt+"/(1-"+mt+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SMTZcuts+")*"+mt+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LMuZ+SMTZcuts+")*"+mte+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
cout << "Background for MMMT = " << lv << " +- " << ler << endl;
e->cd();
eleEleMuTauEventTreeID->cd();
eventTree->Draw("1>>l(1,1,2)","("+LEleZ+SMTZcuts+")*"+mt+"/(1-"+mt+")");
double lv = l->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SMTZcuts+")*"+mt+"^2");
double ler1 = le->GetBinContent(1);
eventTree->Draw("1>>le(1,1,2)","("+LEleZ+SMTZcuts+")*"+mte+"");
double ler2 = le->GetBinContent(1);
double ler = sqrt(ler1+ler2*ler2);
cout << "Background for EEMT = " << lv << " +- " << ler << endl;


////////////////////////////// Integral Method for Leptons /////////////////////////////////////////////
double IFREle,IFREleErr,IFRMu,IFRMuErr;
IFREle = NE/DE;
IFREleErr = sqrt(NE/(DE*DE)+NE*NE/(DE*DE*DE));
IFRMu = NM/DM;
IFRMuErr = sqrt(NM/(DM*DM)+NM*NM/(DM*DM*DM));
cout << "Integral ele fakerate = " << IFREle << " +- " << IFREleErr << endl;
cout << "Integral mu fakerate = " << IFRMu << " +- " << IFRMuErr << endl;
e->cd();
eleEleEleEleEventTreeID->cd();
double EEEE = eventTree->GetEntries(LEleZ+SEEZcuts);
double eeee = IFREle*IFREle*EEEE/(1-IFREle*IFREle);
double eeeeErr = sqrt(EEEE*IFREle*IFREle*IFREle*IFREle+4*IFREleErr*IFREleErr*EEEE*EEEE*IFREle*IFREle);
cout << "Background Est. for EEEE = " << eeee << " +- " << eeeeErr << endl;
//cout << "Events In Control Region " << EEEE << endl;
e->cd();
eleEleEleMuEventTreeID->cd();
double EEEM = eventTree->GetEntries(LEleZ+SEMZcuts);
double eeem = IFREle*IFRMu*EEEM/(1-IFREle*IFRMu);
double eeemErr = sqrt(EEEM*IFREle*IFREle*IFRMu*IFRMu+(IFREleErr*IFREleErr*IFRMu*IFRMu+IFRMuErr*IFRMuErr*IFREle*IFREle)*EEEM*EEEM);
cout << "Background Est. for EEEM = " << eeem << " +- " << eeemErr << endl;
//cout << "Events In Control Region " << EEEM << endl;
m->cd();
muMuEleMuEventTreeID->cd();
double MMEM = eventTree->GetEntries(LMuZ+SEMZcuts);
double mmem = IFREle*IFRMu*MMEM/(1-IFREle*IFRMu);
double mmemErr = sqrt(MMEM*IFREle*IFREle*IFRMu*IFRMu+(IFREleErr*IFREleErr*IFRMu*IFRMu+IFRMuErr*IFRMuErr*IFREle*IFREle)*MMEM*MMEM);
cout << "Background Est. for MMEM = " << mmem << " +- " << mmemErr << endl;
//cout << "Events In Control Region " << MMEM << endl;
m->cd();
muMuEleEleEventTreeID->cd();
double MMEE = eventTree->GetEntries(LMuZ+SEEZcuts);
double mmee = IFREle*IFREle*MMEE/(1-IFREle*IFREle);
double mmeeErr = sqrt(MMEE*IFREle*IFREle*IFREle*IFREle+4*IFREleErr*IFREleErr*MMEE*MMEE*IFREle*IFREle);
cout << "Background Est. for MMEE = " << mmee << " +- " << mmeeErr << endl;
//cout << "Events In Control Region " << MMEE << endl;
e->cd();
eleEleMuMuEventTreeID->cd();
double EEMM = eventTree->GetEntries(LEleZ+SMMZcuts);
double eemm = IFRMu*IFRMu*EEMM/(1-IFRMu*IFRMu);
double eemmErr = sqrt(EEMM*IFRMu*IFRMu*IFRMu*IFRMu+4*IFRMuErr*IFRMuErr*IFRMu*IFRMu*EEMM*EEMM);
cout << "Background Est. for EEMM = " << eemm << " +- " << eemmErr << endl;
//cout << "Events In Control Region " << EEMM << endl;
m->cd();
muMuMuMuEventTreeID->cd();
double MMMM = eventTree->GetEntries(LMuZ+SMMZcuts);
double mmmm = IFRMu*IFRMu*MMMM/(1-IFRMu*IFRMu);
double mmmmErr = sqrt(MMMM*IFRMu*IFRMu*IFRMu*IFRMu+4*IFRMuErr*IFRMuErr*IFRMu*IFRMu*MMMM*MMMM);
cout << "Background Est. for MMMM = " << mmmm << " +- " << mmmmErr << endl;
//cout << "Events In Control Region " << MMMM << endl;

mm->BayesDivide(nm,dm);
mm->Draw("AP");
C->SaveAs("FitPlots/mu.png");
ee->BayesDivide(ne,de);
ee->Draw("AP");
C->SaveAs("FitPlots/ele.png");


}